import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { CategoryComparison, Drawer, TimeSeriesChart } from "./interview";
afterEach(cleanup);
describe("interview shared presentation",()=>{
 it("keeps unknown chart observations as gaps and exposes exact keyboard values with units",()=>{const {container}=render(<TimeSeriesChart label="Wait" points={[{at:"2026-01-01T00:00:00Z",values:{wait:2}},{at:"2026-01-02T00:00:00Z",values:{wait:null}},{at:"2026-01-10T00:00:00Z",values:{wait:7.25}}]} series={[{id:"wait",label:"Wait",unit:"days",color:"navy"}]} note="Source observations"/>);expect(container.querySelectorAll('line[stroke="navy"]')).toHaveLength(0);const chart=screen.getByRole("group",{name:/Wait. Use/});fireEvent.keyDown(chart,{key:"End"});expect(screen.getByRole("status")).toHaveTextContent("Wait: 7.25 days");fireEvent.keyDown(chart,{key:"ArrowLeft"});expect(screen.getByRole("status")).toHaveTextContent("No observation");});
 it("keeps categorical result labels and denominator details distinct with inspectable evidence",()=>{const inspect=vi.fn();render(<CategoryComparison label="Conversion" unit="percent" observations={[{id:"earlier",label:"Earlier",value:30,valueLabel:"30%",detail:"6 / 20 mature"},{id:"later",label:"Later",value:null,valueLabel:"Unavailable",detail:"2 observing",unavailableReason:"No mature cohort"}]} onInspect={inspect}/>);expect(screen.getByText("6 / 20 mature")).toBeVisible();expect(screen.getByText("No mature cohort")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Inspect Later"}));expect(inspect).toHaveBeenCalledWith("later");});
 it("uses a supplied percentage scale without changing values and retains safe automatic scaling",()=>{const observations=[{id:"cohort",label:"Cohort",value:55,valueLabel:"55%",detail:"11 / 20 mature"}];const {container,rerender}=render(<CategoryComparison label="Conversion" unit="%" observations={observations} scaleMaximum={100} benchmark={{value:50,label:"Target"}}/>);expect(Number.parseFloat((container.querySelector(".ip2-category__track i") as HTMLElement).style.width)).toBeCloseTo(55);expect(container.querySelector(".ip2-category__track b")).toHaveStyle({left:"50%"});expect(screen.getByText("55%")).toBeVisible();rerender(<CategoryComparison label="Conversion" unit="%" observations={observations}/>);expect(container.querySelector(".ip2-category__track i")).toHaveStyle({width:"100%"});rerender(<CategoryComparison label="Conversion" unit="%" observations={observations} scaleMaximum={20}/>);expect(container.querySelector(".ip2-category__track i")).toHaveStyle({width:"100%"});rerender(<CategoryComparison label="Conversion" unit="%" observations={observations} scaleMaximum={Number.NaN}/>);expect(container.querySelector(".ip2-category__track i")).toHaveStyle({width:"100%"});});
 it("focuses the drawer close control and returns to the opener on dismissal",()=>{const {rerender}=render(<button type="button">Open details</button>);const opener=screen.getByRole("button");opener.focus();const close=vi.fn();rerender(<><button type="button">Open details</button><Drawer title="Details" onClose={close}><p>Prepared facts</p></Drawer></>);expect(screen.getByRole("button",{name:"Close Details"})).toHaveFocus();fireEvent.click(screen.getByRole("button",{name:"Close Details"}));expect(close).toHaveBeenCalledOnce();rerender(<button type="button">Open details</button>);expect(screen.getByRole("button")).toHaveFocus();});
});
