import { useEffect, useId, useRef, useState } from "react";
import type { ReactNode } from "react";

import { displayDate } from "./presentationFormat";
export function Panel({ title, tools, children, className = "" }: { title: string; tools?: ReactNode; children: ReactNode; className?: string }) { return <section className={`panel ip2-panel ${className}`}><header><h2>{title}</h2>{tools}</header>{children}</section>; }
export function Drawer({ title, eyebrow, children, onClose, closeLabel }: { title: string; eyebrow?: string; children: ReactNode; onClose: () => void; closeLabel?: string }) {
  const ref = useRef<HTMLDialogElement>(null); const titleId = useId();
  useEffect(() => { const opener = document.activeElement as HTMLElement | null; const dialog = ref.current; if (dialog?.showModal) dialog.showModal(); else dialog?.setAttribute("open", ""); dialog?.querySelector<HTMLButtonElement>("button")?.focus(); return () => { dialog?.close?.(); if (opener?.isConnected) opener.focus(); }; }, []);
  return <dialog ref={ref} className="ip2-drawer" aria-labelledby={titleId} onCancel={(event) => { event.preventDefault(); onClose(); }}><header>{eyebrow ? <small>{eyebrow}</small> : null}<button type="button" aria-label={closeLabel ?? `Close ${title}`} onClick={onClose}>×</button><h2 id={titleId}>{title}</h2></header><div className="ip2-drawer__body">{children}</div></dialog>;
}
export interface ChartPoint { readonly at: string; readonly phase?: "historical" | "forecast"; readonly values: Readonly<Record<string, number | null>>; }
export interface ChartSeries { readonly id: string; readonly label: string; readonly color: string; readonly unit: string; }
/** Geometry only: callers supply every metric and source-backed observation. */
export function TimeSeriesChart({ label, points, series, boundaryAt, threshold, note }: { label: string; points: readonly ChartPoint[]; series: readonly ChartSeries[]; boundaryAt?: string; threshold?: { value: number; label: string }; note: string }) {
  const host = useRef<HTMLDivElement>(null); const [width, setWidth] = useState(700); const [selected, setSelected] = useState<number | null>(null);
  useEffect(() => { if (!host.current || typeof ResizeObserver === "undefined") return; const observer = new ResizeObserver(([entry]) => setWidth(Math.max(240, entry?.contentRect.width ?? 700))); observer.observe(host.current); return () => observer.disconnect(); }, []);
  if (!points.length) return <p className="ip2-scope">No observations are available for this selection.</p>;
  const height = 270, left = 42, right = width - 18, top = 20, bottom = height - 35;
  const start = Date.parse(points[0]!.at), end = Date.parse(points.at(-1)!.at); const maximum = Math.max(1, threshold?.value ?? 0, ...points.flatMap((p) => series.map((s) => p.values[s.id] ?? 0))); const step = Math.max(1, Math.ceil(maximum / 4)); const ceiling = step * 4;
  const x = (at: string) => left + (Date.parse(at) - start) / Math.max(1, end - start) * (right - left); const y = (value: number) => bottom - value / ceiling * (bottom - top);
  const active = selected === null ? null : points[Math.min(selected, points.length - 1)];
  const nearest = (clientX: number) => { const box = host.current?.getBoundingClientRect(); if (!box) return; const position = clientX - box.left; let index = 0; points.forEach((p, i) => { if (Math.abs(x(p.at) - position) < Math.abs(x(points[index]!.at) - position)) index = i; }); setSelected(index); };
  return <figure className="ip2-chart"><div className="ip2-chart__legend">{series.map((s) => <span key={s.id}><i style={{ background: s.color }} />{s.label} · {s.unit}</span>)}</div><div ref={host} className="ip2-chart__plot"><svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`} role="group" tabIndex={0} aria-label={`${label}. Use left and right arrow keys to inspect observations.`} onPointerMove={(e) => nearest(e.clientX)} onPointerDown={(e) => nearest(e.clientX)} onKeyDown={(e) => { if (["ArrowLeft", "ArrowRight", "Home", "End"].includes(e.key)) { e.preventDefault(); setSelected(e.key === "Home" ? 0 : e.key === "End" ? points.length - 1 : Math.max(0, Math.min(points.length - 1, (selected ?? 0) + (e.key === "ArrowLeft" ? -1 : 1)))); } }}>
  {[0,1,2,3,4].map((i) => <g key={i}><line x1={left} x2={right} y1={y(i * step)} y2={y(i * step)} stroke="#e3e8e6" /><text x={left - 10} y={y(i * step) + 4} textAnchor="end">{i * step}</text></g>)}
  {boundaryAt && Date.parse(boundaryAt) >= start && Date.parse(boundaryAt) < end ? <g><rect x={x(boundaryAt)} y={top} width={right - x(boundaryAt)} height={bottom - top} fill="#fbf5e7" opacity=".5" /><line x1={x(boundaryAt)} x2={x(boundaryAt)} y1={top} y2={bottom} stroke="#7f91a9" strokeDasharray="3 4" /><text x={Math.min(right - 80, x(boundaryAt) + 7)} y={top + 12}>Projection →</text></g> : null}
  {threshold ? <g><line x1={left} x2={right} y1={y(threshold.value)} y2={y(threshold.value)} stroke="#b27d2c" strokeDasharray="5 4" /><text x={right} y={y(threshold.value) - 5} textAnchor="end">{threshold.label}</text></g> : null}
  {series.map((s) => <g key={s.id}>{points.map((p, i) => { const previous = points[i - 1]; const value = p.values[s.id]; const prior = previous?.values[s.id]; return previous && value !== null && value !== undefined && prior !== null && prior !== undefined ? <line key={p.at} x1={x(previous.at)} x2={x(p.at)} y1={y(prior)} y2={y(value)} stroke={s.color} strokeWidth="2.2" strokeDasharray={p.phase === "forecast" ? "6 4" : undefined} /> : null; })}</g>)}
  {[0,1,2,3].map((i) => { const index = Math.round((points.length - 1) * i / 3); return <text key={i} x={x(points[index]!.at)} y={height - 9} textAnchor={i === 0 ? "start" : i === 3 ? "end" : "middle"}>{new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(points[index]!.at))}</text>; })}
  {active ? <g><line x1={x(active.at)} x2={x(active.at)} y1={top} y2={bottom} stroke="#17345f" />{series.map((s) => active.values[s.id] !== null && active.values[s.id] !== undefined ? <circle key={s.id} cx={x(active.at)} cy={y(active.values[s.id]!)} r="4" fill={s.color} stroke="white" /> : null)}</g> : null}</svg></div><output className="ip2-chart__readout" aria-live="polite">{active ? <><strong>{displayDate(active.at)} · {new Date(active.at).toISOString().slice(11,16)} UTC · {active.phase === "forecast" ? "Projected" : "Observed"}</strong>{series.map((s) => <span key={s.id}>{s.label}: {active.values[s.id] ?? "No observation"} {s.unit}</span>)}</> : "Point or use the arrow keys to inspect an exact observation."}</output><figcaption>{note}</figcaption></figure>;
}

export interface CategoryObservation { readonly id: string; readonly label: string; readonly value: number | null; readonly valueLabel: string; readonly detail: string; readonly unavailableReason?: string; }
/** Categorical comparisons never connect cohorts into a time trend. */
export function CategoryComparison({ label, unit, observations, benchmark, onInspect }: { label: string; unit: string; observations: readonly CategoryObservation[]; benchmark?: { value: number; label: string }; onInspect?: (id: string) => void }) {
 const maximum = Math.max(1, benchmark?.value ?? 0, ...observations.map((o) => o.value ?? 0));
 return <figure className="ip2-category" aria-label={label}><figcaption>{label} · {unit}</figcaption>{observations.map((o) => <div className="ip2-category__row" key={o.id}><div><strong>{o.label}</strong><small>{o.detail}</small></div><div className="ip2-category__track">{o.value !== null ? <i style={{width:`${o.value / maximum * 100}%`}}/> : null}{benchmark ? <b title={benchmark.label} style={{left:`${benchmark.value / maximum * 100}%`}}/> : null}</div><div><strong>{o.valueLabel}</strong>{o.unavailableReason ? <small>{o.unavailableReason}</small> : null}{onInspect ? <button type="button" onClick={() => onInspect(o.id)} aria-label={`Inspect ${o.label}`}>Inspect</button> : null}</div></div>)}{benchmark ? <p>{benchmark.label}: {benchmark.value} {unit}</p> : null}</figure>;
}
