import { useMemo, useState } from "react";
import type { FormEvent } from "react";
import type { DemoActionContext, ProcessDraftSavePayload, ProgramDecisionSavePayload, ProgramTextSavePayload, WorkCreatePayload, WorkspaceNavigationTarget } from "../../contracts/v2";
import type { PreparedProgramRow, PreparedProgramsView, ProgramResultGroup } from "../../logic/programs";
import { CategoryComparison, Drawer, Panel } from "../../ui/interview";
import { displayDate, displayNumber } from "../../ui/presentationFormat";
import "./programs.css";

export interface ProgramsScreenActions {
  readonly onOpenEvidence: (evidenceId: string) => void;
  readonly onSaveProgramText?: (payload: ProgramTextSavePayload) => void | Promise<void>;
}
interface Props {
  readonly view: PreparedProgramsView;
  readonly actions: ProgramsScreenActions;
  readonly commandContext?: DemoActionContext;
  readonly onNavigateTarget?: (target: WorkspaceNavigationTarget) => void;
  readonly onSaveDecision?: (payload: ProgramDecisionSavePayload) => void | Promise<void>;
  readonly onSaveDraft?: (payload: ProcessDraftSavePayload) => void | Promise<void>;
  readonly onCreateLinkedWork?: (payload: WorkCreatePayload) => void | Promise<void>;
}
type Surface = "detail" | "decision" | "draft" | "work" | "text";
const statuses = [{ id: "all", label: "All" }, { id: "trying", label: "Running" }, { id: "reviewing", label: "Review now" }, { id: "rolling-out", label: "Expanding" }, { id: "closed", label: "Stopped" }, { id: "idea", label: "Ideas" }] as const;
const stageLabel = (stage: string) => statuses.find((item) => item.id === stage)?.label ?? stage;
const percent = (value: number) => `${displayNumber(value * 100)}%`;
const amount = (value: number, unit: string, currency: string | null) => unit === "ratio" ? percent(value) : unit === "currency-minor" && currency ? new Intl.NumberFormat("en-US", { style: "currency", currency }).format(value / 100) : `${displayNumber(value)} ${unit}`;
const resultLabel = (group: ProgramResultGroup | null) => !group ? "Inspect cohorts" : group.result === null ? group.unit === "currency-minor" ? "Cost unavailable" : "Still observing" : amount(group.result, group.unit, group.currency);
const goalLabel = (row: PreparedProgramRow) => { const value = row.targetDetails.value ?? row.targetDetails.benchmark; const group = row.result ?? row.groups[0]; return value === null || !group ? "No declared target" : `${amount(value, group.unit, group.currency)}${row.targetDetails.value === null ? " · benchmark only" : ""}`; };
const dateInput = (value: string) => value.slice(0, 10);
const enteredDate = (value: string) => `${value}T17:00:00.000Z` as ProgramDecisionSavePayload["nextReviewAt"];

function Cohorts({ row, view, inspect }: { row: PreparedProgramRow; view: PreparedProgramsView; inspect: (evidenceId: string) => void }) {
  const first = row.groups[0];
  if (!first) return <p className="ip2-scope">No enrolled cohort in this selection.</p>;
  const points = view.cohortComparisons.filter((point) => point.programId === row.id);
  const target = row.targetDetails.value;
  const chartValue = (value: number) => first.unit === "ratio" ? value * 100 : first.unit === "currency-minor" ? value / 100 : value;
  return <><CategoryComparison label={`${first.outcomeLabel} · ${first.followUpDays}-day horizon`} unit={first.unit === "ratio" ? "%" : first.currency ?? first.unit} scaleMaximum={first.unit === "ratio" ? 100 : undefined} observations={row.groups.map((group, index) => ({
    id: String(group.evidence.id), label: group.label, tone: index === 0 ? "navy" : "green", value: group.result === null ? null : chartValue(group.result), valueLabel: resultLabel(group),
    detail: `${group.matureEntrants} mature · ${group.stillObservingEntrants} observing${group.unit === "ratio" && group.evidence.computation.status === "available" ? ` · ${group.evidence.computation.numerator} / ${group.evidence.computation.denominator}` : ""}`,
    unavailableReason: group.evidence.computation.status === "unavailable" ? group.evidence.computation.reason : undefined,
  }))} benchmark={target === null ? undefined : { value: chartValue(target), label: "Declared target (applicable cohort)" }} onInspect={inspect} />
  <p className="ip2-scope">{points.map((point) => `${row.groups.find((group) => group.groupId === point.groupId)?.label ?? point.groupId}: ${point.targetState === "met" ? "Target met in this sample" : point.targetState === "not-met" ? "Below target" : point.targetState === "unavailable" ? "Target not yet evaluable" : "No compatible cohort target"}`).join(" · ")}. Descriptive frozen cohorts, not causal proof. Administrative stage: {stageLabel(row.stage)}.</p>
  {row.targetDetails.reason ? <p className="ip2-scope">{goalLabel(row)}. {row.targetDetails.reason}</p> : null}</>;
}

function ProcessSteps({ row, owners }: { row: PreparedProgramRow; owners: PreparedProgramsView["ownerOptions"] }) {
  return <>{row.processVersions.map((version) => <section key={version.id}><h3>Readiness checklist · v{version.version} · {version.status}</h3><p>{version.trigger}</p><p>Owner: {owners.find((owner) => owner.id === version.ownerId)?.label ?? "Recorded owner"} · Next review: {displayDate(version.nextReviewAt)}</p>{version.requiredSteps.map((step) => <div className="ip2-review-row" key={step.id}><small>{step.responsibleRole ?? "Responsible role not recorded"} · {step.slaElapsedHours === undefined ? "SLA not recorded" : `${step.slaElapsedHours}h SLA`}</small><strong className="programs__block">{step.instruction}</strong><p>Evidence: {step.evidenceRequirement || "Not recorded"}</p><p>Exception: {step.exceptionRoute ?? "Not recorded in this version"}</p></div>)}<p>Exceptions: {version.exceptions.join(" · ") || "None recorded"}</p></section>)}{row.processVersions.length === 0 ? <p>No canonical process version recorded for this program.</p> : null}{row.processGaps.length ? <p>Some historical steps lack accountability fields. Inspect the recorded version before copying it.</p> : null}</>;
}

/** Prepared source values and canonical callbacks only; local state holds filters and entered form drafts. */
export function ProgramsScreen({ view, actions, commandContext, onNavigateTarget, onSaveDecision, onSaveDraft, onCreateLinkedWork }: Props) {
  const [mode, setMode] = useState<"Programs" | "Results">("Programs");
  const [query, setQuery] = useState(""); const [type, setType] = useState("All"); const [status, setStatus] = useState("all"); const [sort, setSort] = useState("default");
  const [selectedId, setSelectedId] = useState<string | null>(null); const [surface, setSurface] = useState<Surface | null>(null); const [evidenceId, setEvidenceId] = useState<string | null>(null);
  const [owner, setOwner] = useState(""); const [review, setReview] = useState(""); const [rationale, setRationale] = useState(""); const [decision, setDecision] = useState<ProgramDecisionSavePayload["decision"]>("continue"); const [sourceVersion, setSourceVersion] = useState("");
  const [workTitle, setWorkTitle] = useState(""); const [domain, setDomain] = useState<WorkCreatePayload["domain"]>("program"); const [priority, setPriority] = useState<NonNullable<WorkCreatePayload["priority"]>>("normal"); const [due, setDue] = useState("");
  const [note, setNote] = useState(""); const [nextStep, setNextStep] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [confirmation, setConfirmation] = useState("");
  const exactDrill = view.appliedFilters.programIds.length > 0 || view.appliedFilters.recordRefs.length > 0;
  const scoped = useMemo(() => view.rows.filter((row) => exactDrill || ([row.title, row.marketLabel, row.brief, row.nextStep, row.workflowSource].join(" ").toLowerCase().includes(query.trim().toLowerCase()) && (type === "All" || row.typeLabel === type))), [view.rows, exactDrill, query, type]);
  const rows = useMemo(() => scoped.filter((row) => exactDrill || status === "all" || row.stage === status).sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : sort === "review" ? a.reviewAt.localeCompare(b.reviewAt) : 0), [scoped, exactDrill, status, sort]);
  const selected = rows.find((row) => row.id === selectedId) ?? rows[0] ?? null;
  const disabled = pending || commandContext?.busy;
  const clear = () => { setQuery(""); setType("All"); setStatus("all"); setSort("default"); };
  const open = (row: PreparedProgramRow, next: Surface = "detail", exactEvidence?: string) => {
    setSelectedId(row.id); setSurface(next); setEvidenceId(exactEvidence ?? String(row.result?.evidence.id ?? row.groups[0]?.evidence.id ?? "")); setError(""); setConfirmation("");
    setOwner(row.ownerId); setReview(""); setRationale(""); setDecision("continue"); setSourceVersion(""); setWorkTitle(""); setDomain("program"); setPriority("normal"); setDue(""); setNote(row.latestNote ?? ""); setNextStep(row.latestNextStep ?? row.nextStep);
  };
  const navigate = (target: WorkspaceNavigationTarget) => { setSurface(null); requestAnimationFrame(() => onNavigateTarget?.(target)); };
  const save = async (event: FormEvent, operation: () => void | Promise<void>, success: string) => { event.preventDefault(); if (disabled) return; setPending(true); setError(""); setConfirmation(""); try { await operation(); setConfirmation(success); } catch (reason) { setError(reason instanceof Error ? reason.message : "Save failed. Your entries are retained; try again."); } finally { setPending(false); } };
  const requireReview = () => { if (!review || !commandContext || Date.parse(enteredDate(review)) <= Date.parse(commandContext.occurredAt)) throw new Error("Choose a next review date after the current demo date."); if (!owner) throw new Error("Choose an accountable owner."); };
  const ownerField = <label>Accountable owner<select aria-label="Accountable owner" required value={owner} onChange={(event) => setOwner(event.target.value)}><option value="">Choose owner</option>{view.ownerOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>;
  const reviewField = <label>Next review date<input required type="date" min={commandContext ? dateInput(commandContext.occurredAt) : undefined} value={review} onChange={(event) => setReview(event.target.value)} /></label>;
  const formTitle = surface === "decision" ? "Record program decision" : surface === "draft" ? "Save process draft" : surface === "work" ? "Create linked work" : surface === "text" ? "Edit notes and next step" : selected?.title ?? "Program";
  return <main aria-label="Programs" className="workspace ip2-workspace programs">
    <section aria-label="Program metrics" className="kpi-strip"><div><span>Running</span><strong>{view.summary.running}</strong></div><div><span>Review now</span><strong>{view.summary.reviewNow}</strong></div><div><span>Expanding</span><strong>{view.summary.expanding}</strong></div><div><span>Stopped</span><strong>{view.summary.stopped}</strong></div></section>
    <div aria-label="Programs view controls" className="workspace-controls">{(["Programs", "Results"] as const).map((item) => <button aria-pressed={mode === item} className={mode === item ? "is-active" : undefined} key={item} onClick={() => setMode(item)} type="button">{item}</button>)}</div>
    <section className="panel ip2-filters" aria-label="Program filters">{statuses.filter((item) => item.id === "all" || scoped.some((row) => row.stage === item.id)).map((item) => <button key={item.id} type="button" disabled={exactDrill} aria-pressed={status === item.id} className={status === item.id ? "is-active" : undefined} onClick={() => setStatus(status === item.id ? "all" : item.id)}>{item.label} {item.id === "all" ? scoped.length : scoped.filter((row) => row.stage === item.id).length}</button>)}<input className="programs__search" aria-label="Find program" disabled={exactDrill} type="search" placeholder="Find a program…" value={query} onChange={(event) => setQuery(event.target.value)} /><label>Type <select aria-label="Type" disabled={exactDrill} value={type} onChange={(event) => setType(event.target.value)}>{["All", "Experiment", "Campaign", "Sourcing", "Process"].map((item) => <option key={item} value={item}>{item === "All" ? "All types" : item}</option>)}</select></label><select aria-label="Sort programs" value={sort} onChange={(event) => setSort(event.target.value)}><option value="default">Default order</option><option value="title">Program A–Z</option><option value="review">Review date</option></select><button type="button" onClick={clear}>Clear all</button></section>
    <p className="ip2-scope">{rows.length} results · Market, status, type and search scope the table, chart and attention. KPIs show the selected market before local filters.{exactDrill ? " Exact linked record selection temporarily takes precedence over retained local filters; Clear drill-down restores them." : ""} {view.filterScope.unsupported.join(" ")}</p>
    <section className="attention-chart"><Panel title="What needs attention" className="attention" tools={<span>{Math.min(rows.length, 3)} items</span>}><ol>{rows.slice(0, 3).map((row, index) => <li key={row.id}><b>{index + 1}</b><div><small>{row.marketLabel} · {stageLabel(row.stage)}</small><strong><button type="button" onClick={() => open(row)}>{row.title}</button></strong><span>{row.stage === "closed" ? "Inspect stop rationale and recorded spend." : row.stage === "trying" ? "Inspect the observation window and next action." : "Inspect completed cohorts and the next decision."}</span></div></li>)}</ol>{!rows.length ? <p className="ip2-scope">No programs match these filters.</p> : null}</Panel><Panel title={selected?.title ?? "Cohort results"} tools={rows.length > 1 ? <select aria-label="Comparison program" value={selected?.id ?? ""} onChange={(event) => setSelectedId(event.target.value)}>{rows.map((row) => <option key={row.id} value={row.id}>{row.title}</option>)}</select> : undefined}>{selected ? <><Cohorts row={selected} view={view} inspect={(id) => open(selected, "detail", id)} /><div className="ip2-cohort-actions"><button type="button" onClick={() => open(selected)}>Inspect result and decision →</button></div></> : <p className="ip2-scope">Clear filters to inspect program results.</p>}</Panel></section>
    {mode === "Results" ? <Panel title="Results and observation">{rows.map((row) => <div className="programs__result" key={row.id}><h3>{row.title}</h3><Cohorts row={row} view={view} inspect={(id) => open(row, "detail", id)} /><button type="button" onClick={() => open(row)}>Inspect {row.title}</button></div>)}</Panel> : null}
    <Panel title="Programs" tools={<span>{rows.length} shown</span>}><div className="table-scroll"><table><thead><tr><th>Type</th><th>Program / status</th><th>Market</th><th>Brief</th><th>Start / review</th><th>Goal</th><th>Results so far</th><th>Notes / next step</th><th>Source</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.typeLabel}</td><th><button type="button" onClick={() => open(row)}>{row.title}</button><small className="programs__block">{stageLabel(row.stage)}</small></th><td>{row.marketLabel}</td><td>{row.brief}</td><td>{displayDate(row.implementationAt)}<small>Review {displayDate(row.reviewAt)}</small></td><td>{goalLabel(row)}<small>{(row.result ?? row.groups[0])?.outcomeLabel}</small></td><td>{resultLabel(row.result)}<small>{row.result ? `${row.result.matureEntrants} mature · ${row.result.stillObservingEntrants} observing` : row.resultSelectionReason}</small></td><td><button type="button" onClick={() => open(row, "text")}>Edit notes &amp; next step</button><small>{row.latestNote ?? "No note recorded"}</small><small>{row.latestNextStep ?? row.nextStep}</small></td><td>{row.workflowSource}</td></tr>)}</tbody></table></div></Panel>
    {surface && selected ? <Drawer title={formTitle} eyebrow={surface === "detail" ? "Program detail" : "Program action"} onClose={() => { if (!pending) setSurface(null); }}>
      <p>{selected.title} · {selected.marketLabel} · {stageLabel(selected.stage)} · {selected.owner?.fictionalName ?? "Owner not recorded"}</p>
      {surface === "detail" ? <><h3>Problem and hypothesis</h3><p>{selected.brief}</p><p>{selected.hypothesis}</p><p>Eligibility: {selected.eligibilityRule}</p><h3>Results and observation</h3><Cohorts row={selected} view={view} inspect={(id) => setEvidenceId(id)} /><p>{selected.resultSelectionReason}</p>{evidenceId ? <button type="button" onClick={() => { const id = evidenceId; setSurface(null); requestAnimationFrame(() => actions.onOpenEvidence(id)); }}>Why this?</button> : null}
        {selected.groups.map((group) => <details key={group.groupId}><summary>{group.label} · observation and source details</summary><p>Entry window: {group.evidence.reportingWindow ? `${displayDate(group.evidence.reportingWindow.startAt)}–${displayDate(group.evidence.reportingWindow.endAt)} (end exclusive)` : "Not recorded"}. {group.followUpDays}-day follow-up from entry. {group.stillObservingEntrants === 0 && group.matureEntrants > 0 ? "Completed cohort observation." : "Observation ongoing."}</p><p>{group.evidence.explanation}</p>{group.sourceContributions.map((source) => <p key={source.sourceId ?? "unknown"}>{source.sourceLabel} · Direct spend: {source.attributableSpendMinor === null ? "Unavailable" : amount(source.attributableSpendMinor, "currency-minor", source.currency)}. {source.reason} {source.allocation} {source.exclusions.join(" ")}</p>)}</details>)}
        <h3>Target and retained decision</h3><p>{goalLabel(selected)} · {selected.targetDetails.label}</p><p>{selected.targetDetails.reason}</p>{selected.latestDecision ? <><p>{selected.latestDecision.decision} · {displayDate(selected.latestDecision.decidedAt)}</p><p>{selected.latestDecision.rationale}</p></> : <p>No decision recorded.</p>}<p>Accountable owner: {selected.owner?.fictionalName ?? "Not recorded"} · Next review: {displayDate(selected.reviewAt)}</p>
        <div className="ip2-actions"><button type="button" onClick={() => open(selected, "decision")}>Record decision</button><button type="button" onClick={() => open(selected, "draft")} disabled={!selected.processVersions.length}>Save process draft</button><button type="button" onClick={() => open(selected, "work")}>Create linked work</button><button type="button" onClick={() => open(selected, "text")}>Edit notes &amp; next step</button></div>
        <ProcessSteps row={selected} owners={view.ownerOptions} /><h3>Participant checklist and next action</h3><p>{selected.latestNextStep ?? selected.nextStep}</p><details><summary>Inspect participant checklist records ({selected.participants.length})</summary>{selected.participants.map((participant) => <div key={participant.enrollment.id} className="ip2-review-row"><strong>{participant.name} · {participant.enrollment.groupId}</strong>{participant.onboardingSteps.length ? participant.onboardingSteps.map((step) => <p key={step.id}>{step.stepDefinitionId} · {step.state} · {step.assignedTo ? view.ownerOptions.find((option) => option.id === step.assignedTo)?.label ?? "Recorded owner" : "Unassigned"}{step.dueAt ? ` · due ${displayDate(step.dueAt)}` : ""}{step.blockerCode ? ` · blocker ${step.blockerCode}` : ""} · {step.evidenceRef ? "Evidence recorded" : "Evidence missing"}</p>) : <p>No onboarding steps recorded.</p>}</div>)}</details>
        <h3>Linked Team work</h3>{selected.work.map(({ record, target }) => <div className="ip2-review-row" key={record.id}><button type="button" disabled={!onNavigateTarget} onClick={() => navigate(target)}>{record.title ?? record.kind}</button><p>{record.kind} · {record.priority ?? "Priority not recorded"}{record.dueAt ? ` · due ${displayDate(record.dueAt)}` : ""}{record.blockerCode ? ` · blocked: ${record.blockerCode}` : ""}</p><details><summary>Assignment history</summary>{record.ownerHistory.map((change, index) => <p key={index}>{change.ownerId ? view.ownerOptions.find((option) => option.id === change.ownerId)?.label ?? "Recorded owner" : "Unassigned"} · {displayDate(change.occurredAt)}</p>)}</details></div>)}{!selected.work.length ? <p>No linked work recorded.</p> : null}
        {selected.workaround ? <details><summary>Original manual workaround</summary><p>{selected.workaround.purpose}</p><div className="table-scroll"><table><thead><tr>{selected.workaround.columnDefinitions.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{selected.workaround.rows.map((row, i) => <tr key={i}>{row.cells.map((cell) => <td key={cell.columnKey}>{cell.value}</td>)}</tr>)}</tbody></table></div></details> : null}{selected.historyLimitations.map((text) => <p key={text}>{text}</p>)}
      </> : <><p>Acting as {commandContext?.actor?.name ?? "No active actor"} · {commandContext ? displayDate(commandContext.occurredAt) : "Current demo time unavailable"}</p>
        {surface === "decision" ? <form onSubmit={(event) => void save(event, async () => { requireReview(); if (!rationale.trim()) throw new Error("Enter a decision rationale."); if (!onSaveDecision) throw new Error("Decision saving is unavailable."); await onSaveDecision({ programId: selected.id, decision, rationale, ownerId: owner as ProgramDecisionSavePayload["ownerId"], nextReviewAt: enteredDate(review) }); }, "Decision saved. Current evidence is retained; no automatic rollout.")}><p>Bounded expansion creates review work. It does not roll out a process.</p><div className="ip2-form"><label>Decision<select aria-label="Decision" value={decision} onChange={(event) => setDecision(event.target.value as typeof decision)}><option value="continue">Continue</option><option value="change">Change / iterate</option><option value="stop">Stop</option><option value="expand">Expand — bounded review</option></select></label>{ownerField}{reviewField}<label className="programs__wide">Decision rationale<textarea required value={rationale} onChange={(event) => setRationale(event.target.value)} /></label></div><button disabled={disabled || !commandContext?.actor || !!confirmation} type="submit">{pending ? "Saving…" : "Save decision"}</button></form> : null}
        {surface === "draft" ? <form onSubmit={(event) => void save(event, async () => { requireReview(); if (!sourceVersion) throw new Error("Select a canonical source process version."); if (!onSaveDraft) throw new Error("Draft saving is unavailable."); await onSaveDraft({ programId: selected.id, sourceProcessVersionId: sourceVersion as ProcessDraftSavePayload["sourceProcessVersionId"], ownerId: owner as ProcessDraftSavePayload["ownerId"], nextReviewAt: enteredDate(review) }); }, "Process draft saved from the selected canonical version. No rollout or enrollment changed.")}><p>Copies the selected version's actual steps, trigger and exceptions into a new draft.</p><div className="ip2-form"><label>Source process version<select aria-label="Source process version" required value={sourceVersion} onChange={(event) => setSourceVersion(event.target.value)}><option value="">Choose a recorded version</option>{selected.processVersions.map((version) => <option key={version.id} value={version.id}>Version {version.version} · {version.status}</option>)}</select></label>{ownerField}{reviewField}</div>{sourceVersion ? <ProcessSteps row={{ ...selected, processVersions: selected.processVersions.filter((version) => version.id === sourceVersion) }} owners={view.ownerOptions} /> : null}<button type="submit" disabled={disabled || !commandContext?.actor || !!confirmation}>{pending ? "Saving…" : "Save draft"}</button></form> : null}
        {surface === "work" ? <form onSubmit={(event) => void save(event, async () => { if (!onCreateLinkedWork) throw new Error("Linked work saving is unavailable."); await onCreateLinkedWork({ programId: selected.id, title: workTitle, ownerId: owner ? owner as WorkCreatePayload["ownerId"] : null, domain, status: "open", dueAt: due ? enteredDate(due) : null, priority, primaryEntityRef: { kind: "program", id: selected.id } }); }, "Linked Team work saved. Program outcomes are unchanged.")}><div className="ip2-form"><label className="programs__wide">Work title<input required value={workTitle} onChange={(event) => setWorkTitle(event.target.value)} /></label><label>Owner<select aria-label="Owner" value={owner} onChange={(event) => setOwner(event.target.value)}><option value="">Unassigned</option>{view.ownerOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label><label>Domain<select aria-label="Domain" value={domain} onChange={(event) => setDomain(event.target.value as typeof domain)}>{["program", "sourcing", "screening", "onboarding", "market"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Due date<input type="date" value={due} onChange={(event) => setDue(event.target.value)} /></label><label>Priority<select aria-label="Priority" value={priority} onChange={(event) => setPriority(event.target.value as typeof priority)}>{["low", "normal", "high", "urgent"].map((item) => <option key={item}>{item}</option>)}</select></label></div><button type="submit" disabled={disabled || !commandContext?.actor || !!confirmation}>{pending ? "Saving…" : "Save linked work"}</button></form> : null}
        {surface === "text" ? <form onSubmit={(event) => void save(event, async () => { if (!actions.onSaveProgramText) throw new Error("Text saving is unavailable."); await actions.onSaveProgramText({ programId: selected.id, field: "note", text: note }); await actions.onSaveProgramText({ programId: selected.id, field: "next-step", text: nextStep }); }, "Notes and next step saved. Program outcomes and decisions do not change.")}><div className="ip2-form"><label className="programs__wide">Notes<textarea aria-label={`Notes for ${selected.title}`} value={note} onChange={(event) => { setNote(event.target.value); setConfirmation(""); }} /></label><label className="programs__wide">Next step<textarea aria-label={`Next step for ${selected.title}`} value={nextStep} onChange={(event) => { setNextStep(event.target.value); setConfirmation(""); }} /></label></div><button type="submit" disabled={disabled}>{pending ? "Saving…" : "Save notes and next step"}</button></form> : null}
        <div className="ip2-actions"><button type="button" disabled={pending} onClick={() => { setSurface("detail"); setError(""); setConfirmation(""); }}>Back to program</button></div>
      </>}{error ? <p role="alert">{error} Your entries are retained.</p> : null}{confirmation ? <p role="status">{confirmation}</p> : null}
    </Drawer> : null}
  </main>;
}
