import { useState } from "react";
import type { CoachingAction, EvidenceBundleId, TeamTarget, UtcTimestamp, WorkQualityCheck } from "../../contracts/v2";
import type { TeamMemberView } from "../../logic/team";
import { Drawer } from "../../ui/interview";
import { displayDate, displayDateRange, displayNumber } from "../../ui/presentationFormat";
import type { TeamScreenProps } from "./index";

const stamp = (value: string) => `${value}:00Z` as UtcTimestamp;
export function MemberDrawer({ view, member, actions, commandContext, onCreateRecordId, onClose, onOpenWork, onEvidence }: TeamScreenProps & { member: TeamMemberView; onClose: () => void; onOpenWork: (id: string) => void; onEvidence: (id: EvidenceBundleId) => void }) {
  const [tab, setTab] = useState<"Overview" | "Goal" | "Quality" | "Coaching" | "Learning">("Overview");
  const [targetId, setTargetId] = useState(member.completed.targetId ?? "");
  const [targetValue, setTargetValue] = useState(member.completed.target?.toString() ?? "");
  const [rationale, setRationale] = useState("");
  const [workId, setWorkId] = useState("");
  const [checkCode, setCheckCode] = useState("");
  const [checkReason, setCheckReason] = useState("");
  const [passed, setPassed] = useState("passed");
  const [observation, setObservation] = useState("");
  const [practice, setPractice] = useState("");
  const [nextAction, setNextAction] = useState("");
  const [dueAt, setDueAt] = useState("");
  const [reviewAt, setReviewAt] = useState("");
  const [reviewNotes, setReviewNotes] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [feedback, setFeedback] = useState("");
  const disabled = busy || commandContext?.busy || !commandContext?.actor;
  const revision = member.targetRevisions.find((item) => item.target.id === targetId);
  const window = revision?.target.reportingWindow ?? member.completed.window;
  const metric = revision?.target.metric ?? view.evidence[0]?.metric;
  const memberWork = view.workDetails.filter((item) => item.ownerId === member.id || member.coachingActions.some((action) => action.linkedWorkItemIds.includes(item.id as never)) || member.quality.sample.some((sample) => sample.workItemId === item.id));
  async function save(operation: () => Promise<void>, message: string, after?: () => void) {
    if (disabled) return;
    setBusy(true); setFeedback(""); setError("");
    try { await operation(); setFeedback(message); after?.(); }
    catch (failure) { setError(failure instanceof Error ? failure.message : "Save failed. Review the fields and retry."); }
    finally { setBusy(false); }
  }
  function saveTarget() {
    if (!commandContext?.actor || !onCreateRecordId || !window || !metric) return;
    const target: TeamTarget = { id: onCreateRecordId("team-target") as TeamTarget["id"], teamMemberId: revision ? revision.target.teamMemberId : member.id as TeamTarget["teamMemberId"], role: revision ? revision.target.role : member.role, metric, target: Number(targetValue), reportingWindow: window, createdAt: commandContext.occurredAt, rationale, provenance: "demo-simulation" };
    void save(() => actions.onSaveTargetRevision({ target, supersedesTargetId: revision?.target.id ?? null }), "Goal revision saved. Observed work is unchanged.", () => setTargetId(target.id));
  }
  function saveQuality() {
    if (!commandContext?.actor || !onCreateRecordId) return;
    const qualityCheck: WorkQualityCheck = { id: onCreateRecordId("work-quality-check") as WorkQualityCheck["id"], workItemId: workId as WorkQualityCheck["workItemId"], checkedBy: commandContext.actor.memberId, checkedAt: commandContext.occurredAt, requiredCheckResults: [{ checkCode, passed: passed === "passed", reason: checkReason }], outcome: passed as WorkQualityCheck["outcome"], provenance: "demo-simulation" };
    void save(() => actions.onRecordQuality({ qualityCheck }), "Inspection saved for this sample.");
  }
  function saveCoaching() {
    if (!commandContext?.actor || !onCreateRecordId) return;
    const coachingAction: CoachingAction = { id: onCreateRecordId("coaching-action") as CoachingAction["id"], teamMemberId: member.id as CoachingAction["teamMemberId"], linkedWorkItemIds: [workId as CoachingAction["linkedWorkItemIds"][number]], observedIssueOrStrength: observation, expectedPractice: practice, nextAction, dueAt: stamp(dueAt), reviewAt: stamp(reviewAt), outcomeNote: null, authorId: commandContext.actor.actorId, createdAt: commandContext.occurredAt, updatedAt: commandContext.occurredAt, provenance: "demo-simulation" };
    void save(() => tab === "Learning" ? actions.onSharePractice({ coachingAction }) : actions.onRecordCoaching({ coachingAction }), tab === "Learning" ? "Practice-sharing action saved." : "Coaching action saved.");
  }
  const workSelect = <label className="team-form-wide">Linked work<select aria-label="Linked work" required value={workId} onChange={(event) => setWorkId(event.target.value)}><option value="">Select a case to inspect</option>{memberWork.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>;
  return <Drawer title={member.name} eyebrow={member.role} onClose={onClose}>
    <p className="ip2-scope">{commandContext?.actor ? `Acting as ${commandContext.actor.name} · ${displayDate(commandContext.occurredAt)}` : "An active manager is required to save."}</p>
    <div className="workspace-controls" aria-label="Member detail views">{(["Overview", "Goal", "Quality", "Coaching", "Learning"] as const).map((item) => <button type="button" key={item} aria-pressed={item === tab} className={item === tab ? "is-active" : undefined} onClick={() => { setTab(item); setError(""); setFeedback(""); }}>{item}</button>)}</div>
    {tab === "Overview" ? <><dl className="ip2-facts"><div><dt>Open work · all markets</dt><dd>{member.totalOpenWorkload}</dd></div><div><dt>Selected market / filtered work</dt><dd>{member.selectedMarketOpenWorkload} / {member.filteredOpenWorkload}</dd></div><div><dt>Overdue / due unknown</dt><dd>{member.overdueWorkload} / {member.unknownDueWorkload}</dd></div><div><dt>Completed tasks / comparable target</dt><dd>{member.completed.completed} / {member.completed.target ?? "—"}</dd></div></dl><p>{member.completed.note}</p><h3>Assigned work</h3>{member.workItems.map((item) => <div className="ip2-review-row" key={item.id}><button type="button" onClick={() => onOpenWork(item.id)}>{item.label}</button><p>{item.currentStatus} · {item.dueAt ? `Due ${displayDate(item.dueAt)}` : "Due date unknown"}{item.isOverdue ? " · Overdue" : ""}</p></div>)}<h3>Cycle-time samples</h3>{member.cycleTime.completedSamples.map((item) => <p key={item.workItemId}>{item.label} · {displayNumber(item.elapsedHours)} hours completed</p>)}{member.cycleTime.waitingSamples.map((item) => <p key={item.workItemId}>{item.label} · {displayNumber(item.ageHours)} hours waiting</p>)}{!member.cycleTime.completedSamples.length && !member.cycleTime.waitingSamples.length ? <p>No samples in this selection.</p> : null}</> : null}
    {tab === "Goal" ? <><h3>Role target · {revision?.unit ?? "tasks"}</h3><p>{window ? displayDateRange(window.startAt, window.endAt) : "A reporting window is required."}</p><p>{member.completed.note}</p><form aria-label="Save goal" onSubmit={(event) => { event.preventDefault(); saveTarget(); }}><fieldset className="team-form-fields ip2-form" disabled={disabled || !onCreateRecordId || !window || !metric}><label className="team-form-wide">Target revision<select aria-label="Target revision" value={targetId} onChange={(event) => { setTargetId(event.target.value); setTargetValue(member.targetRevisions.find((item) => item.target.id === event.target.value)?.target.target.toString() ?? ""); }}><option value="">New member target for displayed window</option>{member.targetRevisions.map((item) => <option key={item.target.id} value={item.target.id}>{item.target.target} {item.unit ?? "unit unknown"} · {displayDate(item.target.createdAt)} · {item.target.teamMemberId ? "Member" : "Role"}{item.selectedForComparison ? " · Compared" : ""}</option>)}</select></label><label>Target ({revision?.unit ?? "tasks"})<input type="number" min="0" step="any" required value={targetValue} onChange={(event) => setTargetValue(event.target.value)} /></label><label>Population<input value={revision?.target.teamMemberId === null ? `Role: ${revision.target.role}` : `${member.name} · ${member.role}`} readOnly /></label><label className="team-form-wide">Rationale<textarea required rows={3} value={rationale} onChange={(event) => setRationale(event.target.value)} /></label><button type="submit">Save goal revision</button></fieldset></form><details><summary>Target history</summary>{member.targetRevisions.map((item) => <p key={item.target.id}>{item.target.target} {item.unit ?? "unknown unit"} · {displayDateRange(item.target.reportingWindow.startAt, item.target.reportingWindow.endAt)} · {item.target.rationale} · {item.selectedForComparison ? "Used for comparison" : "Not compared in this selection"}</p>)}</details></> : null}
    {tab === "Quality" ? <><h3>Inspected quality</h3><p>{member.quality.passedCount} / {member.quality.inspectedCount} inspected work passed · {member.quality.ratio === null ? "No ratio available" : new Intl.NumberFormat("en-US", { style: "percent", maximumFractionDigits: 1 }).format(member.quality.ratio)}</p><p>{member.quality.scope}</p>{member.quality.sample.map((item) => <div className="ip2-review-row" key={item.id}><button type="button" onClick={() => onOpenWork(item.workItemId)}>{item.label}</button><p>{item.passed ? "Passed" : "Needs follow-up"} · Inspected by {item.reviewerName} · {displayDate(item.checkedAt)} · Owner at inspection: {item.subjectName}</p>{item.requiredCheckResults.map((check) => <p key={check.checkCode}>{check.checkCode}: {check.passed ? "Passed" : "Needs follow-up"} · {check.reason}</p>)}</div>)}<form aria-label="Record quality inspection" onSubmit={(event) => { event.preventDefault(); saveQuality(); }}><fieldset className="team-form-fields ip2-form" disabled={disabled || !onCreateRecordId}>{workSelect}<label>Required check<input required value={checkCode} onChange={(event) => setCheckCode(event.target.value)} /></label><label>Result<select aria-label="Result" value={passed} onChange={(event) => setPassed(event.target.value)}><option value="passed">Passed</option><option value="needs-follow-up">Needs follow-up</option></select></label><label className="team-form-wide">Inspection reason<textarea required rows={3} value={checkReason} onChange={(event) => setCheckReason(event.target.value)} /></label><button type="submit">Record inspection</button></fieldset></form></> : null}
    {tab === "Coaching" || tab === "Learning" ? <><h3>{tab === "Learning" ? "Share a successful practice" : "Coaching and next review"}</h3><form aria-label={tab === "Learning" ? "Share practice" : "Record coaching"} onSubmit={(event) => { event.preventDefault(); saveCoaching(); }}><fieldset className="team-form-fields ip2-form" disabled={disabled || !onCreateRecordId}>{workSelect}<label className="team-form-wide">{tab === "Learning" ? "Observed strength" : "Observed issue or strength"}<textarea required rows={2} value={observation} onChange={(event) => setObservation(event.target.value)} /></label><label className="team-form-wide">Expected practice<textarea required rows={2} value={practice} onChange={(event) => setPractice(event.target.value)} /></label><label className="team-form-wide">Next action<input required value={nextAction} onChange={(event) => setNextAction(event.target.value)} /></label><label>Due date (UTC)<input type="datetime-local" required value={dueAt} onChange={(event) => setDueAt(event.target.value)} /></label><label>Review date (UTC)<input type="datetime-local" required value={reviewAt} onChange={(event) => setReviewAt(event.target.value)} /></label><button type="submit">{tab === "Learning" ? "Share practice" : "Save coaching action"}</button></fieldset></form><h3>Recorded coaching and practice</h3>{member.coachingDetails.length ? member.coachingDetails.map(({ action, reviewContentAvailable, limitation }) => <article className="ip2-review-row" key={action.id}><strong>{action.observedIssueOrStrength}</strong><p>{action.expectedPractice}</p><p>Next: {action.nextAction}</p><p>Due {displayDate(action.dueAt)} · Review {displayDate(action.reviewAt)} · Original author {action.authorId}</p>{action.linkedWorkItemIds.map((id) => <button type="button" key={id} onClick={() => onOpenWork(id)}>{view.workDetails.find((item) => item.id === id)?.title ?? "Inspect linked work"}</button>)}<p>{reviewContentAvailable ? action.outcomeNote ?? "Review pending" : limitation}</p><form aria-label={`Review ${action.observedIssueOrStrength}`} onSubmit={(event) => { event.preventDefault(); if (!commandContext) return; void save(() => actions.onReviewCoaching({ coachingActionId: action.id, reviewedAt: commandContext.occurredAt, outcomeNote: reviewNotes[action.id] ?? "" }), "Review saved; original author retained."); }}><label>Review result<textarea required value={reviewNotes[action.id] ?? ""} onChange={(event) => setReviewNotes({ ...reviewNotes, [action.id]: event.target.value })} /></label><button type="submit" disabled={disabled}>Save review</button></form></article>) : <p>No coaching records in this selection.</p>}</> : null}
    {error ? <p role="alert">{error}</p> : null}{feedback ? <p role="status">{feedback}</p> : null}
    <details><summary>Measurement and scope</summary>{view.scopeNotes.map((note) => <p key={note}>{note}</p>)}{view.evidence.filter((item) => item.id.includes(member.id)).map((item) => <button type="button" key={item.id} onClick={() => onEvidence(item.id)}>Inspect {item.id.includes("quality") ? "inspected tasks (count)" : item.id.includes("completed") ? "completed tasks" : item.id.includes("waiting") ? "waiting work" : "open work"}</button>)}</details>
  </Drawer>;
}
