import type { AssignmentEvent, AvailabilityStatus, CapabilityVerification, DemoSnapshotV2, EvidenceBundle, MarketId, ReadinessEvent, ReporterId, ResolvedRecordReference, UtcTimestamp, WorkspaceLogicPort, WorkspaceQueryContext } from "../../contracts/v2";

export const NETWORK_WORKSPACE = "reporters" as const;
export type NetworkLogicPort = WorkspaceLogicPort<typeof NETWORK_WORKSPACE>;
type AvailabilityState = AvailabilityStatus | "expired";
export interface NetworkReporterRow { readonly reporterId: ReporterId; readonly name: string; readonly serviceMarkets: readonly MarketId[]; readonly readinessAt: UtcTimestamp; readonly availability: AvailabilityState; readonly capabilitySummary: string; readonly lastCompletedJobAt: UtcTimestamp | null; readonly recentJobCount: number; readonly followUp: "create-reengagement-task" | "open-task" | null; }
export interface NetworkTrendPoint { readonly windowStartAt: UtcTimestamp; readonly windowEndAt: UtcTimestamp; readonly activeReporterIds: readonly ReporterId[]; readonly firstTimeEnteringReporterIds: readonly ReporterId[]; readonly returningReporterIds: readonly ReporterId[]; readonly noRecentWorkReporterIds: readonly ReporterId[]; }
export interface PreparedNetworkView { readonly workspace: typeof NETWORK_WORKSPACE; readonly evaluation: WorkspaceQueryContext<typeof NETWORK_WORKSPACE>["evaluation"]; readonly appliedFilters: WorkspaceQueryContext<typeof NETWORK_WORKSPACE>["filters"]; readonly evidence: readonly EvidenceBundle[]; readonly reporters: readonly NetworkReporterRow[]; readonly trend: readonly NetworkTrendPoint[]; readonly reengagementCandidates: readonly NetworkReporterRow[]; }

const asMillis = (value: UtcTimestamp) => Date.parse(value);
const atOrBefore = (value: UtcTimestamp, asOfAt: UtcTimestamp) => asMillis(value) <= asMillis(asOfAt);
const isKnown = (occurredAt: UtcTimestamp, recordedAt: UtcTimestamp, asOfAt: UtcTimestamp) => atOrBefore(occurredAt, asOfAt) && atOrBefore(recordedAt, asOfAt);
const pointer = (kind: ResolvedRecordReference["kind"], id: string) => ({ kind, id });
const dateWindow = (endAt: UtcTimestamp, days: number) => new Date(asMillis(endAt) - days * 86_400_000).toISOString() as UtcTimestamp;
function completedJobs(snapshot: DemoSnapshotV2, asOfAt: UtcTimestamp) { return snapshot.jobOutcomes.filter((job) => job.outcome === "completed" && job.completedAt !== null && isKnown(job.completedAt, job.recordedAt, asOfAt)); }
/** Earliest valid completion is global to the reporter, never duplicated by service market. */
export function firstCompletedJobs(snapshot: DemoSnapshotV2, asOfAt: UtcTimestamp) { const firstByReporter = new Map<ReporterId, ReturnType<typeof completedJobs>[number]>(); for (const job of completedJobs(snapshot, asOfAt).sort((left, right) => asMillis(left.completedAt!) - asMillis(right.completedAt!))) if (!firstByReporter.has(job.reporterId)) firstByReporter.set(job.reporterId, job); return [...firstByReporter.values()]; }
function latestReadiness(snapshot: DemoSnapshotV2, reporterId: ReporterId, asOfAt: UtcTimestamp): ReadinessEvent | null { return snapshot.readinessEvents.filter((event) => event.reporterId === reporterId && isKnown(event.occurredAt, event.recordedAt, asOfAt)).sort((left, right) => asMillis(right.occurredAt) - asMillis(left.occurredAt))[0] ?? null; }
function availabilityAt(snapshot: DemoSnapshotV2, reporterId: ReporterId, asOfAt: UtcTimestamp): AvailabilityState { const current = snapshot.availabilityWindows.filter((window) => window.reporterId === reporterId && atOrBefore(window.recordedAt, asOfAt) && asMillis(window.startAt) <= asMillis(asOfAt) && asMillis(asOfAt) < asMillis(window.endAt)).sort((left, right) => asMillis(right.recordedAt) - asMillis(left.recordedAt))[0]; if (!current) return "unknown"; if (current.confirmationExpiresAt !== null && asMillis(current.confirmationExpiresAt) <= asMillis(asOfAt)) return "expired"; return current.status; }
function capabilitySummary(capabilities: readonly CapabilityVerification[], reporterId: ReporterId, asOfAt: UtcTimestamp) { const current = capabilities.filter((item) => item.reporterId === reporterId && atOrBefore(item.recordedAt, asOfAt)); const verified = current.filter((item) => item.status === "verified").length; const unknown = current.filter((item) => item.status === "unreviewed" || item.status === "needs-information").length; const notDemonstrated = current.filter((item) => item.status === "not-demonstrated").length; return current.length ? `${verified} verified; ${unknown} unknown; ${notDemonstrated} not demonstrated` : "No capability verification recorded"; }
function currentWorkStatus(snapshot: DemoSnapshotV2, reporterId: ReporterId, asOfAt: UtcTimestamp) { return snapshot.workItems.filter((item) => { if (item.primaryEntityRef.kind !== "reporter" || item.primaryEntityRef.id !== reporterId) return false; const latest = item.statusHistory.filter((change) => atOrBefore(change.occurredAt, asOfAt)).sort((left, right) => asMillis(right.occurredAt) - asMillis(left.occurredAt))[0]; return latest !== undefined && ["open", "in-progress", "blocked"].includes(latest.status); }); }
function isClosed(snapshot: DemoSnapshotV2, reporterId: ReporterId, asOfAt: UtcTimestamp) { const latest = snapshot.lifecycleEvents.filter((event) => event.reporterId === reporterId && isKnown(event.occurredAt, event.recordedAt, asOfAt)).sort((left, right) => asMillis(right.occurredAt) - asMillis(left.occurredAt))[0]; return latest?.eventType === "closed"; }
function reporterReference(snapshot: DemoSnapshotV2, reporterId: ReporterId): ResolvedRecordReference { const reporter = snapshot.reporters.find((item) => item.id === reporterId); return { ...pointer("reporter", reporterId), label: reporter?.fictionalName ?? String(reporterId), occurredAt: reporter?.createdAt ?? null, joinPath: [] }; }
function networkEvidence(snapshot: DemoSnapshotV2, context: WorkspaceQueryContext<typeof NETWORK_WORKSPACE>, rows: readonly NetworkReporterRow[]): EvidenceBundle { const metric = snapshot.metricDefinitions.find((definition) => String(definition.id) === "M10"); if (!metric) throw new Error("Network view requires the frozen M10 metric definition."); const recent = rows.filter((row) => row.recentJobCount > 0); const references = recent.map((row) => reporterReference(snapshot, row.reporterId)); const filters = { ...context.filters, reporterIds: recent.map((row) => row.reporterId), recordRefs: references.map((reference) => pointer(reference.kind, reference.id)) }; return { id: `evidence-network-recent-${context.evaluation.snapshotRevision}` as EvidenceBundle["id"], metric: { id: metric.id, version: metric.version }, asOfAt: context.evaluation.asOfAt, snapshotRevision: context.evaluation.snapshotRevision, unit: "people", scope: { workspace: NETWORK_WORKSPACE, marketBasis: "job-market", selectedMarket: context.filters.selectedMarket, populationDescription: "Distinct ready reporters with a completed job in the trailing 28 elapsed days." }, filters, reportingWindow: { startAt: dateWindow(context.evaluation.asOfAt, 28), endAt: context.evaluation.asOfAt, boundary: "[start,end)" }, computation: { status: "available", value: recent.length, numerator: null, denominator: null }, contributingRecords: references, numeratorMembers: [], denominatorMembers: [], exclusions: [], unknownCount: rows.filter((row) => row.availability === "unknown" || row.availability === "expired").length, limitations: ["Recently working is not an availability claim.", "No recent work is not attrition or unwillingness."], explanation: `${recent.length} distinct ready reporters completed work in the trailing 28 elapsed days; availability is shown separately.`, navigationTarget: { workspace: NETWORK_WORKSPACE, intent: "evidence-list", filters, evidenceContext: { asOfAt: context.evaluation.asOfAt, snapshotRevision: context.evaluation.snapshotRevision, metric: { id: metric.id, version: metric.version } } } }; }
export function prepareNetworkView(snapshot: DemoSnapshotV2, context: WorkspaceQueryContext<typeof NETWORK_WORKSPACE>): PreparedNetworkView { const asOfAt = context.evaluation.asOfAt; const recentStart = dateWindow(asOfAt, 28); const jobs = completedJobs(snapshot, asOfAt); const rows: NetworkReporterRow[] = snapshot.reporters.flatMap((reporter): NetworkReporterRow[] => { const readiness = latestReadiness(snapshot, reporter.id, asOfAt); if (!readiness || isClosed(snapshot, reporter.id, asOfAt) || (context.filters.selectedMarket !== "ALL" && !reporter.serviceMarketIds.includes(context.filters.selectedMarket))) return []; const reporterJobs = jobs.filter((job) => job.reporterId === reporter.id); const lastCompletedJobAt = reporterJobs.map((job) => job.completedAt!).sort((a, b) => asMillis(b) - asMillis(a))[0] ?? null; const recentJobCount = reporterJobs.filter((job) => asMillis(job.completedAt!) >= asMillis(recentStart)).length; const openWork = currentWorkStatus(snapshot, reporter.id, asOfAt); const reengagement = recentJobCount === 0 && lastCompletedJobAt !== null; const followUp: NetworkReporterRow["followUp"] = reengagement ? (openWork.length ? "open-task" : "create-reengagement-task") : null; return [{ reporterId: reporter.id, name: reporter.fictionalName, serviceMarkets: reporter.serviceMarketIds, readinessAt: readiness.occurredAt, availability: availabilityAt(snapshot, reporter.id, asOfAt), capabilitySummary: capabilitySummary(snapshot.capabilityVerifications, reporter.id, asOfAt), lastCompletedJobAt, recentJobCount, followUp }]; }); const priorStart = dateWindow(asOfAt, 35); const active = new Set(rows.filter((row) => row.recentJobCount > 0).map((row) => row.reporterId)); const priorActive = new Set(jobs.filter((job) => asMillis(job.completedAt!) >= asMillis(priorStart) && asMillis(job.completedAt!) < asMillis(dateWindow(asOfAt, 7))).map((job) => job.reporterId)); const entering = [...active].filter((id) => !priorActive.has(id)); const firstTime = entering.filter((id) => !jobs.some((job) => job.reporterId === id && asMillis(job.completedAt!) < asMillis(priorStart))); const trend: NetworkTrendPoint = { windowStartAt: recentStart, windowEndAt: asOfAt, activeReporterIds: [...active], firstTimeEnteringReporterIds: firstTime, returningReporterIds: entering.filter((id) => !firstTime.includes(id)), noRecentWorkReporterIds: [...priorActive].filter((id) => !active.has(id)) }; return { workspace: NETWORK_WORKSPACE, evaluation: context.evaluation, appliedFilters: context.filters, evidence: [networkEvidence(snapshot, context, rows)], reporters: rows, trend: [trend], reengagementCandidates: rows.filter((row) => row.followUp !== null) }; }
export function acceptedCommitmentIssues(snapshot: DemoSnapshotV2, asOfAt: UtcTimestamp): readonly string[] { const latest = new Map<string, AssignmentEvent>(); for (const event of snapshot.assignmentEvents.filter((item) => isKnown(item.occurredAt, item.recordedAt, asOfAt)).sort((a, b) => asMillis(a.occurredAt) - asMillis(b.occurredAt))) latest.set(`${event.requestId}:${event.reporterId}`, event); const commitments = [...latest.values()].filter((event) => event.state === "accepted"); const issues: string[] = []; for (let i = 0; i < commitments.length; i += 1) for (let j = i + 1; j < commitments.length; j += 1) { const left = commitments[i]!; const right = commitments[j]!; const leftRequest = snapshot.demandRequests.find((item) => item.id === left.requestId); const rightRequest = snapshot.demandRequests.find((item) => item.id === right.requestId); if (!leftRequest || !rightRequest) continue; if (left.requestId === right.requestId && left.reporterId !== right.reporterId) issues.push(`Request ${left.requestId} has two accepted reporters.`); if (left.reporterId === right.reporterId && asMillis(leftRequest.startAt) < asMillis(rightRequest.endAt) && asMillis(rightRequest.startAt) < asMillis(leftRequest.endAt)) issues.push(`Reporter ${left.reporterId} has overlapping accepted work.`); } return issues; }
export const networkLogic: NetworkLogicPort = { workspace: NETWORK_WORKSPACE, prepare: prepareNetworkView };
