import { describe, expect, it } from "vitest";
import type { DemoSnapshotV2, WorkspaceQueryContext } from "../../contracts/v2";
import { acceptedCommitmentIssues, firstCompletedJobs, NETWORK_WORKSPACE, prepareNetworkView } from "./index";

const at = (value: string) => value as never;
const id = (value: string) => value as never;
const asOf = at("2026-02-16T17:00:00.000Z");
const context = { workspace: NETWORK_WORKSPACE, evaluation: { asOfAt: asOf, snapshotRevision: 3, reportingTimeZone: "America/Los_Angeles" as never }, filters: { selectedMarket: "ALL", marketBasis: "all-markets", marketIds: [], reporterIds: [], acquisitionCaseIds: [], requestIds: [], workItemIds: [], programIds: [], programEnrollmentIds: [], sourceIds: [], jobOutcomeIds: [], capabilityCodes: [], attendanceModes: [], recordRefs: [], window: null } } satisfies WorkspaceQueryContext<typeof NETWORK_WORKSPACE>;
function snapshot(): DemoSnapshotV2 { return { revision: 3, reporters: ["available", "unavailable", "expired", "unknown", "closed"].map((name) => ({ id: id(name), fictionalName: name, serviceMarketIds: ["LAX"], createdAt: at("2025-01-01T00:00:00.000Z"), preferences: {} })), readinessEvents: ["available", "unavailable", "expired", "unknown", "closed"].map((name) => ({ reporterId: id(name), occurredAt: at("2026-01-01T00:00:00.000Z"), recordedAt: at("2026-01-01T00:00:00.000Z") })), availabilityWindows: [{ reporterId: id("available"), startAt: at("2026-02-01T00:00:00.000Z"), endAt: at("2026-03-01T00:00:00.000Z"), recordedAt: asOf, confirmationExpiresAt: at("2026-02-20T00:00:00.000Z"), status: "available" }, { reporterId: id("unavailable"), startAt: at("2026-02-01T00:00:00.000Z"), endAt: at("2026-03-01T00:00:00.000Z"), recordedAt: asOf, confirmationExpiresAt: null, status: "unavailable" }, { reporterId: id("expired"), startAt: at("2026-02-01T00:00:00.000Z"), endAt: at("2026-03-01T00:00:00.000Z"), recordedAt: asOf, confirmationExpiresAt: at("2026-02-16T17:00:00.000Z"), status: "available" }] as never, capabilityVerifications: [{ reporterId: id("available"), recordedAt: asOf, status: "verified" }, { reporterId: id("available"), recordedAt: asOf, status: "needs-information" }] as never, lifecycleEvents: [{ reporterId: id("closed"), eventType: "closed", occurredAt: at("2026-02-15T00:00:00.000Z"), recordedAt: at("2026-02-15T00:00:00.000Z") }] as never, jobOutcomes: [{ requestId: id("req-lax"), reporterId: id("available"), acceptedAssignmentEventId: id("accepted-lax"), outcome: "completed", completedAt: at("2026-02-16T17:00:00.000Z"), recordedAt: asOf }] as never, workItems: [], metricDefinitions: [{ id: id("M10"), version: id("1"), unit: "people" }] as never, assignmentEvents: [{ id: id("accepted-lax"), requestId: id("req-lax"), reporterId: id("available"), state: "accepted", occurredAt: asOf, recordedAt: asOf }] as never, demandRequests: [{ id: id("req-lax"), marketId: "LAX" }] as never } as unknown as DemoSnapshotV2; }

describe("network projections", () => {
  it("keeps unknown, expired, unavailable, and available evidence distinct (D04)", () => { const view = prepareNetworkView(snapshot(), context); expect(Object.fromEntries(view.reporters.map((row) => [row.name, row.availability]))).toEqual({ available: "available", unavailable: "unavailable", expired: "expired", unknown: "unknown" }); expect(view.reporters).toHaveLength(4); });
  it("uses a half-open trailing window and distinct people (M08)", () => { const view = prepareNetworkView(snapshot(), context); expect(view.evidence[0]?.computation).toMatchObject({ value: 1 }); expect(view.trend[0]?.windowStartAt).toBe("2026-01-19T17:00:00.000Z"); expect(view.trend[0]?.activeReporterIds).toEqual([id("available")]); expect(view.evidence[0]?.limitations).toContain("No recent work is not attrition or unwillingness."); });
  it("flags overlap and duplicate accepted slots, while adjacent work is valid (D05)", () => { const state = snapshot(); const request = (key: string, startAt: string, endAt: string) => ({ id: id(key), startAt: at(startAt), endAt: at(endAt) }); (state as { demandRequests: unknown }).demandRequests = [request("a", "2026-02-20T10:00:00.000Z", "2026-02-20T11:00:00.000Z"), request("b", "2026-02-20T10:30:00.000Z", "2026-02-20T11:30:00.000Z"), request("c", "2026-02-20T11:30:00.000Z", "2026-02-20T12:00:00.000Z")] as never; (state as { assignmentEvents: unknown }).assignmentEvents = ["a", "b", "c", "a"].map((requestId, index) => ({ id: id(`event-${index}`), requestId: id(requestId), reporterId: id(index === 3 ? "other" : "available"), state: "accepted", occurredAt: asOf, recordedAt: asOf })); const issues = acceptedCommitmentIssues(state, asOf); expect(issues).toHaveLength(2); expect(issues.join(" ")).toContain("overlapping"); expect(issues.join(" ")).toContain("two accepted"); });
  it("counts a reporter's earliest valid completed job once globally and excludes invalid outcomes (M03)", () => { const state = snapshot(); (state as { jobOutcomes: unknown }).jobOutcomes = [{ requestId: id("req-lax"), reporterId: id("available"), acceptedAssignmentEventId: id("accepted-lax"), outcome: "completed", completedAt: at("2026-01-01T00:00:00.000Z"), recordedAt: asOf }, { requestId: id("orphan"), reporterId: id("available"), acceptedAssignmentEventId: id("missing"), outcome: "completed", completedAt: at("2026-01-02T00:00:00.000Z"), recordedAt: asOf }, { requestId: id("req-lax"), reporterId: id("unavailable"), acceptedAssignmentEventId: id("accepted-lax"), outcome: "completed", completedAt: at("2026-01-03T00:00:00.000Z"), recordedAt: asOf }, { requestId: id("req-declined"), reporterId: id("available"), acceptedAssignmentEventId: id("declined"), outcome: "completed", completedAt: at("2026-01-04T00:00:00.000Z"), recordedAt: asOf }]; (state as { assignmentEvents: unknown }).assignmentEvents = [...state.assignmentEvents, { id: id("declined"), requestId: id("req-declined"), reporterId: id("available"), state: "declined", occurredAt: asOf, recordedAt: asOf }]; expect(firstCompletedJobs(state, asOf)).toHaveLength(1); });
  it("offers a concrete re-engagement action without treating no recent work as attrition (W01)", () => { const state = snapshot(); (state as { reporters: unknown }).reporters = [...state.reporters, { id: id("returning"), fictionalName: "returning", serviceMarketIds: ["ATL"], createdAt: asOf, preferences: {} }]; (state as { readinessEvents: unknown }).readinessEvents = [...state.readinessEvents, { reporterId: id("returning"), occurredAt: at("2025-01-01T00:00:00.000Z"), recordedAt: at("2025-01-01T00:00:00.000Z") }]; (state as { jobOutcomes: unknown }).jobOutcomes = [...state.jobOutcomes, { requestId: id("req-returning"), reporterId: id("returning"), acceptedAssignmentEventId: id("accepted-returning"), outcome: "completed", completedAt: at("2025-10-01T00:00:00.000Z"), recordedAt: at("2025-10-01T00:00:00.000Z") }]; (state as { assignmentEvents: unknown }).assignmentEvents = [...state.assignmentEvents, { id: id("accepted-returning"), requestId: id("req-returning"), reporterId: id("returning"), state: "accepted", occurredAt: at("2025-09-01T00:00:00.000Z"), recordedAt: at("2025-09-01T00:00:00.000Z") }]; (state as { demandRequests: unknown }).demandRequests = [...state.demandRequests, { id: id("req-returning"), marketId: "ATL" }]; const view = prepareNetworkView(state, context); expect(view.reengagementCandidates.map((row) => row.name)).toEqual(["returning"]); expect(view.reengagementCandidates[0]?.followUp).toBe("create-reengagement-task"); });
  it("uses actual job market for M10 while retaining service-market browsing", () => { const state = snapshot(); (state as { reporters: unknown }).reporters = [{ ...state.reporters[0]!, serviceMarketIds: ["LAX", "SFO"] }]; (state as { demandRequests: unknown }).demandRequests = [{ id: id("req-sfo"), marketId: "SFO" }]; (state as { assignmentEvents: unknown }).assignmentEvents = [{ id: id("accepted-sfo"), requestId: id("req-sfo"), reporterId: id("available"), state: "accepted", occurredAt: asOf, recordedAt: asOf }]; (state as { jobOutcomes: unknown }).jobOutcomes = [{ requestId: id("req-sfo"), reporterId: id("available"), acceptedAssignmentEventId: id("accepted-sfo"), outcome: "completed", completedAt: asOf, recordedAt: asOf }]; const laxContext = { ...context, filters: { ...context.filters, selectedMarket: "LAX" as const } }; const view = prepareNetworkView(state, laxContext); expect(view.reporters).toHaveLength(1); expect(view.reporters[0]?.recentJobCount).toBe(0); expect(view.evidence[0]?.scope.marketBasis).toBe("job-market"); expect(view.evidence[0]?.explanation).toContain("trailing 28"); });
});
