import { useMemo, useState } from "react";
import type { EvidenceBundle, ReporterId, UtcTimestamp } from "../../contracts/v2";
import type { NetworkReporterRow, PreparedNetworkView } from "../../logic/network";
import "./network.css";

export interface ConfirmAvailabilityInput { readonly reporterId: ReporterId; readonly confirmedAt: UtcTimestamp; }
export interface ReportersNetworkActions { readonly onConfirmAvailability: (input: ConfirmAvailabilityInput) => void | Promise<void>; readonly onCreateReengagementTask: (reporterId: ReporterId) => void | Promise<void>; readonly onOpenEvidence: (evidence: EvidenceBundle) => void; readonly onOpenRecruitingChecklist: (reporterId: ReporterId) => void; }
export interface ReportersNetworkScreenProps { readonly view: PreparedNetworkView; readonly actions: ReportersNetworkActions; }
const availabilityLabel = (value: NetworkReporterRow["availability"]) => ({ available: "Available", unavailable: "Unavailable", expired: "Confirmation expired", unknown: "Needs confirmation" }[value]);
const activityDays = (at: string | null, asOf: string) => at ? Math.max(0, Math.floor((Date.parse(asOf) - Date.parse(at)) / 86_400_000)) : null;
const complianceLabel = (state: NetworkReporterRow["compliance"]["state"]) => ({ clear: "Clear", expiring: "Expiring", "needs-check": "Needs check" }[state]);
const complianceTone = (state: NetworkReporterRow["compliance"]["state"]) => ({ clear: "under", expiring: "at", "needs-check": "over" }[state]);

export function ReportersNetworkScreen({ view, actions }: ReportersNetworkScreenProps) {
  const [localView, setLocalView] = useState<"ready" | "activity">("ready");
  const [search, setSearch] = useState(""); const [availability, setAvailability] = useState("all"); const [message, setMessage] = useState<string | null>(null);
  const activityRows = view.reporters.filter((row) => row.recentJobCount > 0 || row.followUp !== null);
  const scopedRows = localView === "ready" ? view.reporters : activityRows;
  const rows = useMemo(() => scopedRows.filter((row) => `${row.name} ${row.serviceMarkets.join(" ")} ${row.capabilitySummary} ${row.certificationSummary} ${row.compliance.evidenceLabel}`.toLowerCase().includes(search.toLowerCase()) && (availability === "all" || row.availability === availability)), [availability, scopedRows, search]);
  const attention = [
    ...view.reporters.filter((row) => row.availability === "unknown" || row.availability === "expired").slice(0, 1).map((row) => ({ label: "Now", finding: `Confirm availability for ${row.name}`, action: "Availability evidence needs confirmation." })),
    ...view.reengagementCandidates.slice(0, 1).map((row) => ({ label: "Next", finding: `Reconnect with ${row.name}`, action: row.followUp === "open-task" ? "A re-engagement task is already open." : "Create the prepared re-engagement task." })),
    ...view.reporters.filter((row) => row.compliance.state !== "clear").slice(0, 1).map((row) => ({ label: "Watch", finding: `Review ${row.name}'s credential evidence`, action: row.compliance.evidenceLabel })),
  ].slice(0, 3);
  const ready = view.reporters.length; const active = view.trend[0]?.activeReporterIds.length ?? 0; const inactive = view.reengagementCandidates.length; const licenses = view.reporters.filter((row) => row.compliance.state !== "clear").length;
  const maximum = Math.max(ready, active, inactive, licenses, 1);
  const activity = [["Ready", ready], ["Recently working", active], ["Needs confirmation", licenses], ["Re-engage", inactive]] as const;
  return <main aria-label="Reporters" className="workspace network-reporters">
    <section aria-label="Reporter network summary" className="kpi-strip">{[["Ready", ready], ["Active in 28 days", active], ["Inactive 28+ days", inactive], ["Licenses to check", licenses]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <div aria-label="Reporter views" className="workspace-controls"><button aria-pressed={localView === "ready"} className={localView === "ready" ? "is-active" : undefined} onClick={() => setLocalView("ready")} type="button">Ready</button><button aria-pressed={localView === "activity"} className={localView === "activity" ? "is-active" : undefined} onClick={() => setLocalView("activity")} type="button">Activity</button></div>
    {localView === "ready" ? <section className="attention-chart"><section className="panel attention"><header><h2>What needs attention</h2><span>{attention.length} items</span></header><ol>{attention.map((item, index) => <li key={item.finding}><b>{index + 1}</b><div><small>{item.label}</small><strong>{item.finding}</strong><span>{item.action}</span></div></li>)}</ol></section><ActivityPanel activity={activity} evidence={view.evidence[0]} maximum={maximum} onOpenEvidence={actions.onOpenEvidence} /></section> : <ActivityPanel activity={activity} evidence={view.evidence[0]} maximum={maximum} onOpenEvidence={actions.onOpenEvidence} />}
    {message ? <p className="network-reporters__result" role="status">{message}</p> : null}
    <section className="panel table-panel"><header><h2>{localView === "ready" ? "Reporters" : "Reporter activity"}</h2><span>{rows.length} shown</span><div className="table-controls"><label className="sr-only" htmlFor="reporter-search">Search reporters</label><input id="reporter-search" onChange={(event) => setSearch(event.target.value)} placeholder="Search…" type="search" value={search} /><label className="sr-only" htmlFor="reporter-availability">Availability</label><select id="reporter-availability" onChange={(event) => setAvailability(event.target.value)} value={availability}><option value="all">All availability</option><option value="available">Available</option><option value="unknown">Needs confirmation</option><option value="expired">Confirmation expired</option></select></div></header><div className="table-scroll"><table><thead><tr><th>Reporter</th><th>Market</th><th>Skills</th><th>Certifications</th><th>Preferences</th><th>Last active</th><th>Compliance</th><th>Follow-up</th></tr></thead><tbody>{rows.map((row) => <ReporterRow actions={actions} asOfAt={view.evaluation.asOfAt} key={row.reporterId} onMessage={setMessage} row={row} />)}</tbody></table></div>{rows.length === 0 ? <p className="network-reporters__empty">No reporters match these filters.</p> : null}</section>
  </main>;
}

function ActivityPanel({ activity, evidence, maximum, onOpenEvidence }: { readonly activity: readonly (readonly [string, number])[]; readonly evidence: EvidenceBundle | undefined; readonly maximum: number; readonly onOpenEvidence: (evidence: EvidenceBundle) => void }) {
  return <section className="panel chart-card network-reporters__activity"><header><h2>Reporter activity</h2>{evidence ? <button className="why-this" onClick={() => onOpenEvidence(evidence)} type="button">Why this?</button> : null}</header><p>A quick view of readiness and recent work.</p><div className="network-reporters__bars">{activity.map(([label, value]) => <div key={label}><span>{label}</span><div aria-label={`${label}: ${value}`} aria-valuemax={maximum} aria-valuemin={0} aria-valuenow={value} role="progressbar"><i style={{ width: `${value / maximum * 100}%` }} /></div><strong>{value}</strong></div>)}</div><small>Reporters · trailing 28 elapsed days</small></section>;
}
function ReporterRow({ row, asOfAt, actions, onMessage }: { readonly row: NetworkReporterRow; readonly asOfAt: UtcTimestamp; readonly actions: ReportersNetworkActions; readonly onMessage: (message: string) => void }) {
  const days = activityDays(row.lastCompletedJobAt, asOfAt);
  return <tr><th scope="row">{row.name}</th><td>{row.serviceMarkets.join(", ")}</td><td>{row.capabilitySummary}</td><td>{row.certificationSummary}</td><td>{availabilityLabel(row.availability)}</td><td><span className={`status-tag status-tag--${days === null || days >= 28 ? "over" : "under"}`}>{days === null ? "No completed work" : `${days} days ago`}</span></td><td><span className={`status-tag status-tag--${complianceTone(row.compliance.state)}`}>{complianceLabel(row.compliance.state)}</span><small className="network-reporters__evidence">{row.compliance.evidenceLabel}</small></td><td><div className="network-reporters__actions"><button disabled={row.availability !== "unknown" && row.availability !== "expired"} onClick={() => { void actions.onConfirmAvailability({ reporterId: row.reporterId, confirmedAt: asOfAt }); onMessage(`Availability confirmation requested for ${row.name}. Coverage is unchanged until a reporter accepts.`); }} type="button">Confirm availability</button><button disabled={row.followUp !== "create-reengagement-task"} onClick={() => { void actions.onCreateReengagementTask(row.reporterId); onMessage(`Re-engagement task requested for ${row.name}. No job outcome or acceptance changed.`); }} type="button">Create re-engagement task</button><button onClick={() => actions.onOpenRecruitingChecklist(row.reporterId)} type="button">Inspect checklist</button></div></td></tr>;
}
