import { useState } from "react";
import type { WorkspaceId, WorkspaceNavigationTarget } from "../../contracts/v2";
import type { PreparedMarketsView } from "../../logic/capacity";

export interface MarketsV2ScreenProps { readonly view: PreparedMarketsView; readonly onSelectMarket: (marketId: string) => void; readonly onOpenEvidence: (target: WorkspaceNavigationTarget) => void; readonly onNavigateWorkspace?: (workspace: WorkspaceId) => void; readonly onPreviewGoal: () => void; readonly onSaveGoal: () => void; }
const keys = ["availableSupply", "demand", "neededSupply"] as const;
const names = { availableSupply: "Available", demand: "Demand", neededSupply: "Needed" };
function Chart({ view, projection }: { readonly view: PreparedMarketsView; readonly projection: boolean }) {
  const series = view.supplyDemandSeries; const points = series ? (projection ? series.points : series.points.filter((item) => item.phase === "historical")) : [];
  if (!points.length) return <p>No source-backed chart is available.</p>;
  const max = Math.max(1, ...points.flatMap((item) => [item.availableSupply, item.demand, item.neededSupply])); const x = (index: number) => index * 100 / Math.max(1, points.length - 1); const y = (value: number) => 92 - value * 78 / max;
  const path = (key: typeof keys[number], phase: "historical" | "forecast") => points.filter((item) => item.phase === phase).map((item) => `${x(points.indexOf(item))},${y(item[key])}`).join(" "); const boundary = series ? points.findIndex((item) => item.at === series.forecastBoundaryAt) : -1;
  const ticks = Array.from(new Set([0, Math.floor((points.length - 1) / 3), Math.floor((points.length - 1) * 2 / 3), points.length - 1]));
  return <figure className="rg-chart rg-chart--axis"><p className="chart-summary">Solid lines are known. Dashed lines are projected.</p><div className="rg-chart__plot-wrap"><span className="rg-chart__y-label">Reporter equivalents</span><svg aria-label={`Supply, demand and needed supply; scale zero to ${max}`} role="img" viewBox="0 0 100 100">{[18,50,82].map((line) => <line className="rg-chart__grid" key={line} x1="0" x2="100" y1={line} y2={line} />)}{boundary >= 0 ? <><line className="rg-chart__boundary" x1={x(boundary)} x2={x(boundary)} y1="0" y2="100" /><text className="rg-chart__annotation" x={Math.min(91, x(boundary) + 1)} y="8">Forecast →</text></> : null}{keys.map((key) => <g key={key}><polyline className={`rg-chart__line rg-chart__line--${key}`} points={path(key, "historical")} /><polyline className={`rg-chart__line rg-chart__line--${key} rg-chart__line--forecast`} points={path(key, "forecast")} /></g>)}</svg></div><div className="rg-chart__x-axis">{ticks.map((index) => <span key={index}>{new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(points[index]!.at))}</span>)}</div><span className="rg-chart__x-label">Week</span><figcaption>{keys.map((key) => <span className={`chart-key chart-key--${key}`} key={key}>{names[key]}</span>)}</figcaption></figure>;
}
export function MarketsV2Screen({ view, onSelectMarket, onOpenEvidence, onNavigateWorkspace }: MarketsV2ScreenProps) {
  const [projection, setProjection] = useState(true); const [localView, setLocalView] = useState<"Trends" | "Overview">("Trends"); if (!view.overview) return null; const { kpis, attention } = view.overview;
  const cards = [["Markets", "markets", `${kpis.marketCount.value} markets`, "Compare supply and demand."], ["Funnel", "recruiting", "Onboarding is slow", "See where people get stuck."], ["Team", "team", "Coverage needs attention", "See workload and late work."], ["Programs", "programs", "Review activity", "See results and next decisions."]] as const;
  return <main aria-label="Overview" className="workspace overview"><section aria-label="Overview metrics" className="kpi-strip"><div><span>Markets</span><strong>{kpis.marketCount.value}</strong></div><div><span>Available reporters</span><strong>{kpis.availableReporters.value}</strong></div><div><span>Open jobs</span><strong>{kpis.openSlots.value}</strong></div><div><span>More needed</span><strong>{kpis.projectedAdditionalNeed.value ?? "—"}</strong><small>projected</small></div></section><div aria-label="Overview view controls" className="workspace-controls">{(["Trends", "Overview"] as const).map((item) => <button aria-pressed={localView === item} className={localView === item ? "is-active" : undefined} key={item} onClick={() => setLocalView(item)} type="button">{item}</button>)}<button aria-pressed={projection} className={projection ? "is-active" : undefined} onClick={() => setProjection((item) => !item)} type="button">Projection {projection ? "on" : "off"}</button></div>{localView === "Trends" ? <section className="attention-chart"><section className="panel attention"><header><h2>What needs attention</h2><span>{attention.length} items</span></header><ol>{attention.map((item, index) => <li key={item.id}><b>{index + 1}</b><div><small>{index === 0 ? "Now" : index === 1 ? "Next" : "Watch"}</small><strong>{item.finding}</strong><button onClick={() => onOpenEvidence(view.evidence[0]!.navigationTarget)} type="button">{item.nextAction}</button></div></li>)}</ol></section><section className="panel chart-card"><header><h2>Supply and demand</h2></header><Chart projection={projection} view={view} /></section></section> : null}<section aria-label="Cross-workspace overview" className="overview-summaries">{cards.map(([label, workspace, title, detail]) => <article className="panel" key={label}><span>{label}</span><h2>{title}</h2><p>{detail}</p><button aria-label={`View ${label}`} onClick={() => workspace === "markets" ? setLocalView("Trends") : onNavigateWorkspace?.(workspace)} type="button">View →</button></article>)}</section><section className="panel table-panel"><header><h2>Market comparison</h2></header><div className="table-scroll"><table><thead><tr><th>Market</th><th>Supply</th><th>Demand</th><th>Gap</th><th>Next step</th></tr></thead><tbody>{view.marketRows.map((row) => <tr key={row.marketId}><th><button onClick={() => onSelectMarket(row.marketId)} type="button">{row.marketName}</button></th><td>{row.overview?.supplyDirection.state ?? "—"}</td><td>{row.overview?.demandDirection.state ?? "—"}</td><td>{row.overview?.gap ?? "—"}</td><td>{row.nextAction}</td></tr>)}</tbody></table></div></section></main>;
}
