import type { AcquisitionCase, AcquisitionCaseId, DateWindow, DemoSnapshotV2, EvidenceBundle, EvidenceBundleId, LifecycleEvent, MarketId, MetricDefinitionRef, RecordPointer, Reporter, ReporterId, SourceId, UtcTimestamp, WorkItem } from "../../contracts/v2";
import type { PreparedWorkspaceViewBase, WorkspaceQueryContext } from "../../contracts/v2";

export const RECRUITING_WORKSPACE = "recruiting" as const;
const DAY = 86_400_000;
export type RecruitingStage = "sourced" | "contacted" | "responded" | "screening" | "qualified" | "onboarding" | "ready" | "paused" | "closed" | "first-job-completed" | "not-recorded";
export interface RecruitingAction { readonly kind: "screening" | "onboarding" | "work-item"; readonly label: string; readonly reason: string; readonly assignedTo: string | null; readonly dueAt: UtcTimestamp | null; readonly record: RecordPointer; }
export interface CurrentCaseProjection { readonly acquisitionCaseId: AcquisitionCaseId; readonly reporterId: ReporterId; readonly reporterName: string; readonly stage: RecruitingStage; readonly stageEnteredAt: UtcTimestamp | null; readonly openActions: readonly RecruitingAction[]; }
export interface FunnelProgression { readonly entryWindow: DateWindow; readonly horizonDays: number; readonly matureCaseIds: readonly AcquisitionCaseId[]; readonly observingCaseIds: readonly AcquisitionCaseId[]; readonly stages: readonly { readonly stage: RecruitingStage; readonly caseIds: readonly AcquisitionCaseId[] }[]; }
export interface OnboardingOutcome { readonly entryWindow: DateWindow; readonly matureCaseIds: readonly AcquisitionCaseId[]; readonly observingCaseIds: readonly AcquisitionCaseId[]; readonly timelyCaseIds: readonly AcquisitionCaseId[]; readonly completedToDateCaseIds: readonly AcquisitionCaseId[]; readonly rate: number | null; }
export interface SourceOutcome { readonly sourceId: SourceId | null; readonly label: string; readonly caseIds: readonly AcquisitionCaseId[]; readonly contactedCaseIds: readonly AcquisitionCaseId[]; readonly qualifiedCaseIds: readonly AcquisitionCaseId[]; readonly readyCaseIds: readonly AcquisitionCaseId[]; readonly firstJobCaseIds: readonly AcquisitionCaseId[]; readonly spend: { readonly status: "recorded"; readonly amountMinor: number; readonly currency: string; readonly display: string } | { readonly status: "missing"; readonly display: string }; }
export interface PreparedRecruitingView extends PreparedWorkspaceViewBase<typeof RECRUITING_WORKSPACE> { readonly currentCases: readonly CurrentCaseProjection[]; readonly funnel: FunnelProgression; readonly onboarding: OnboardingOutcome; readonly sources: readonly SourceOutcome[]; }

const ms = (value: UtcTimestamp) => new Date(value).valueOf();
const known = <T extends { readonly occurredAt: UtcTimestamp; readonly recordedAt: UtcTimestamp }>(item: T, asOf: UtcTimestamp) => ms(item.occurredAt) <= ms(asOf) && ms(item.recordedAt) <= ms(asOf);
const inWindow = (window: DateWindow, value: UtcTimestamp) => ms(value) >= ms(window.startAt) && ms(value) < ms(window.endAt);
const caseRef = (id: AcquisitionCaseId): RecordPointer => ({ kind: "acquisition-case", id });
const stageFor = (event: LifecycleEvent): RecruitingStage => event.eventType === "screening-started" ? "screening" : event.eventType === "onboarding-started" ? "onboarding" : event.eventType === "resumed" ? "not-recorded" : event.eventType;
const distinct = <T,>(values: readonly T[]) => [...new Set(values)];

/** One valid globally earliest completion per reporter; no later/cross-market duplicate is a first job. */
export function globallyEarliestCompletedOutcomes(snapshot: DemoSnapshotV2, asOfAt: UtcTimestamp) {
  return snapshot.jobOutcomes.filter((item) => { const accepted = snapshot.assignmentEvents.find((assignment) => assignment.id === item.acceptedAssignmentEventId && assignment.state === "accepted" && assignment.requestId === item.requestId && assignment.reporterId === item.reporterId && known(assignment, asOfAt)); return item.outcome === "completed" && item.completedAt !== null && ms(item.completedAt) <= ms(asOfAt) && ms(item.recordedAt) <= ms(asOfAt) && accepted !== undefined; }).reduce((results, item) => { const earlier = results.get(item.reporterId); if (!earlier || ms(item.completedAt!) < ms(earlier.completedAt!)) results.set(item.reporterId, item); return results; }, new Map<ReporterId, DemoSnapshotV2["jobOutcomes"][number]>());
}
function events(snapshot: DemoSnapshotV2, id: AcquisitionCaseId, asOf: UtcTimestamp) { return snapshot.lifecycleEvents.filter((item) => item.acquisitionCaseId === id && known(item, asOf)).sort((a, b) => ms(a.occurredAt) - ms(b.occurredAt) || ms(a.recordedAt) - ms(b.recordedAt)); }
function openWork(item: WorkItem, asOf: UtcTimestamp) { const status = item.statusHistory.filter((change) => ms(change.occurredAt) <= ms(asOf)).at(-1)?.status; return status !== undefined && status !== "completed" && status !== "canceled"; }
function actions(snapshot: DemoSnapshotV2, acq: AcquisitionCase, asOf: UtcTimestamp): readonly RecruitingAction[] {
  const result: RecruitingAction[] = []; const screening = snapshot.screeningReviews.filter((item) => item.acquisitionCaseId === acq.id && ms(item.reviewedAt) <= ms(asOf) && ms(item.recordedAt) <= ms(asOf)).at(-1);
  if (screening && (screening.outcome === "pending" || screening.outcome === "needs-information" || screening.unresolvedInformation.length > 0)) result.push({ kind: "screening", label: "Resolve screening information", reason: screening.unresolvedInformation.join("; ") || screening.reason, assignedTo: screening.reviewerId, dueAt: null, record: { kind: "screening-review", id: screening.id } });
  for (const step of snapshot.onboardingSteps.filter((item) => item.acquisitionCaseId === acq.id && ms(item.recordedAt) <= ms(asOf) && item.required && item.state !== "completed" && item.state !== "waived")) result.push({ kind: "onboarding", label: `Complete ${step.stepDefinitionId}`, reason: step.blockerCode ? `Blocked: ${step.blockerCode}` : `Required onboarding step is ${step.state}`, assignedTo: step.assignedTo, dueAt: step.dueAt, record: { kind: "onboarding-step", id: step.id } });
  for (const work of snapshot.workItems.filter((item) => openWork(item, asOf) && (item.primaryEntityRef.id === acq.id || item.primaryEntityRef.id === acq.reporterId))) { const owner = work.ownerHistory.filter((change) => ms(change.occurredAt) <= ms(asOf)).at(-1)?.ownerId ?? null; const overdue = work.dueAt !== null && ms(work.dueAt) < ms(asOf); result.push({ kind: "work-item", label: work.kind.replaceAll("-", " "), reason: work.blockerCode ? `Blocked: ${work.blockerCode}` : overdue ? "Open work is overdue" : owner === null ? "Needed action is unowned" : "Concrete work remains open", assignedTo: owner, dueAt: work.dueAt, record: { kind: "work-item", id: work.id } }); }
  return result;
}
export function projectCurrentCases(snapshot: DemoSnapshotV2, asOfAt: UtcTimestamp, selectedMarket: "ALL" | MarketId = "ALL"): readonly CurrentCaseProjection[] { const earliest = globallyEarliestCompletedOutcomes(snapshot, asOfAt); return snapshot.acquisitionCases.filter((item) => selectedMarket === "ALL" || item.ownerMarketId === selectedMarket).map((acq) => { const timeline = events(snapshot, acq.id, asOfAt); const last = timeline.at(-1); const resumedStage = last?.eventType === "resumed" ? [...timeline].reverse().find((event) => event.eventType !== "resumed" && event.eventType !== "paused") : last; const reporter = snapshot.reporters.find((item) => item.id === acq.reporterId) as Reporter; return { acquisitionCaseId: acq.id, reporterId: acq.reporterId, reporterName: reporter.fictionalName, stage: earliest.has(acq.reporterId) ? "first-job-completed" : resumedStage ? stageFor(resumedStage) : "not-recorded", stageEnteredAt: earliest.has(acq.reporterId) ? null : last?.occurredAt ?? null, openActions: actions(snapshot, acq, asOfAt) }; }); }
function reaches(snapshot: DemoSnapshotV2, id: AcquisitionCaseId, stage: RecruitingStage, start: UtcTimestamp, end: number, asOf: UtcTimestamp) { return events(snapshot, id, asOf).some((item) => stageFor(item) === stage && ms(item.occurredAt) >= ms(start) && ms(item.occurredAt) <= end); }
export function funnelProgression(snapshot: DemoSnapshotV2, asOfAt: UtcTimestamp, entryWindow: DateWindow, selectedMarket: "ALL" | MarketId = "ALL"): FunnelProgression { const members = snapshot.acquisitionCases.filter((acq) => (selectedMarket === "ALL" || acq.ownerMarketId === selectedMarket)).map((acq) => ({ acq, contact: events(snapshot, acq.id, asOfAt).find((item) => item.eventType === "contacted" && inWindow(entryWindow, item.occurredAt)) })).filter((item): item is { acq: AcquisitionCase; contact: LifecycleEvent } => item.contact !== undefined); const mature = members.filter((item) => ms(asOfAt) >= ms(item.contact.occurredAt) + 30 * DAY); const stages: RecruitingStage[] = ["contacted", "responded", "screening", "qualified", "onboarding", "ready"]; return { entryWindow, horizonDays: 30, matureCaseIds: mature.map((item) => item.acq.id), observingCaseIds: members.filter((item) => !mature.some((complete) => complete.acq.id === item.acq.id)).map((item) => item.acq.id), stages: stages.map((stage) => ({ stage, caseIds: mature.filter((item) => reaches(snapshot, item.acq.id, stage, item.contact.occurredAt, ms(item.contact.occurredAt) + 30 * DAY, asOfAt)).map((item) => item.acq.id) })) }; }
export function onboardingOutcomes(snapshot: DemoSnapshotV2, asOfAt: UtcTimestamp, entryWindow: DateWindow, selectedMarket: "ALL" | MarketId = "ALL"): OnboardingOutcome { const firstJobs = globallyEarliestCompletedOutcomes(snapshot, asOfAt); const entries = snapshot.acquisitionCases.filter((acq) => selectedMarket === "ALL" || acq.ownerMarketId === selectedMarket).map((acq) => ({ acq, entry: events(snapshot, acq.id, asOfAt).find((item) => item.eventType === "onboarding-started") })).filter((item): item is { acq: AcquisitionCase; entry: LifecycleEvent } => item.entry !== undefined && inWindow(entryWindow, item.entry.occurredAt)); const mature = entries.filter((item) => ms(asOfAt) >= ms(item.entry.occurredAt) + 14 * DAY); const timely = mature.filter((item) => { const job = firstJobs.get(item.acq.reporterId); return job !== undefined && job.completedAt !== null && ms(job.completedAt) >= ms(item.entry.occurredAt) && ms(job.completedAt) <= ms(item.entry.occurredAt) + 14 * DAY; }); const completed = entries.filter((item) => { const job = firstJobs.get(item.acq.reporterId); return job !== undefined && job.completedAt !== null && ms(job.completedAt) >= ms(item.entry.occurredAt); }); return { entryWindow, matureCaseIds: mature.map((item) => item.acq.id), observingCaseIds: entries.filter((item) => !mature.some((complete) => complete.acq.id === item.acq.id)).map((item) => item.acq.id), timelyCaseIds: timely.map((item) => item.acq.id), completedToDateCaseIds: completed.map((item) => item.acq.id), rate: mature.length ? timely.length / mature.length : null }; }
export function sourceOutcomes(snapshot: DemoSnapshotV2, asOfAt: UtcTimestamp, entryWindow: DateWindow, selectedMarket: "ALL" | MarketId = "ALL"): readonly SourceOutcome[] { const jobs = globallyEarliestCompletedOutcomes(snapshot, asOfAt); const cases = snapshot.acquisitionCases.filter((item) => inWindow(entryWindow, item.openedAt) && ms(item.recordedAt) <= ms(asOfAt) && (selectedMarket === "ALL" || item.ownerMarketId === selectedMarket)); const cohortKey = `${entryWindow.startAt}/${entryWindow.endAt}`; const sameWindow = (left: DateWindow, right: DateWindow) => left.startAt === right.startAt && left.endAt === right.endAt; return distinct(cases.map((item) => item.primarySourceId)).map((sourceId) => { const members = cases.filter((item) => item.primarySourceId === sourceId); const ids = members.map((item) => item.id); const at = (stage: RecruitingStage) => members.filter((item) => reaches(snapshot, item.id, stage, entryWindow.startAt, ms(entryWindow.endAt), asOfAt)).map((item) => item.id); const completed = members.filter((item) => jobs.has(item.reporterId)).map((item) => item.id); const records = sourceId === null ? [] : snapshot.sourceSpend.filter((item) => item.sourceId === sourceId && ms(item.occurredAt) <= ms(asOfAt) && (item.attributableWindow === null || sameWindow(item.attributableWindow, entryWindow)) && (item.cohortRef === null || item.cohortRef === cohortKey)); const currencies = distinct(records.map((item) => item.currency)); const total = records.reduce((sum, item) => sum + item.amountMinor, 0); const spend = records.length && currencies.length === 1 ? { status: "recorded" as const, amountMinor: total, currency: currencies[0]!, display: completed.length ? `${total / completed.length} minor ${currencies[0]} per first job` : `No first jobs yet; ${total} minor ${currencies[0]} spent` } : { status: "missing" as const, display: records.length ? "Spend recorded in multiple currencies; no combined rate" : "Spend not recorded" }; return { sourceId, label: snapshot.sources.find((source) => source.id === sourceId)?.label ?? "Source not recorded", caseIds: ids, contactedCaseIds: at("contacted"), qualifiedCaseIds: at("qualified"), readyCaseIds: at("ready"), firstJobCaseIds: completed, spend }; }); }
function metric(snapshot: DemoSnapshotV2, id: string): MetricDefinitionRef { const found = snapshot.metricDefinitions.find((item) => item.id === id); return found ? { id: found.id, version: found.version } : { id: id as MetricDefinitionRef["id"], version: "sample-v1" as MetricDefinitionRef["version"] }; }
function bundle(snapshot: DemoSnapshotV2, context: WorkspaceQueryContext<typeof RECRUITING_WORKSPACE>, id: string, value: number, cases: readonly AcquisitionCaseId[], window: DateWindow | null, explanation: string, ratio?: readonly AcquisitionCaseId[]): EvidenceBundle { const refs = cases.map(caseRef); const filters = { ...context.filters, acquisitionCaseIds: cases, reporterIds: [], window }; const definition = metric(snapshot, id); const unavailable = ratio !== undefined && cases.length === 0; return { id: `evidence-${id.toLowerCase()}` as EvidenceBundleId, metric: definition, asOfAt: context.evaluation.asOfAt, snapshotRevision: context.evaluation.snapshotRevision, unit: ratio ? "ratio" : "people", scope: { workspace: RECRUITING_WORKSPACE, marketBasis: "recruiting-market-at-entry", selectedMarket: context.filters.selectedMarket, populationDescription: "First-time acquisition cases with complete synthetic records." }, filters, reportingWindow: window, computation: unavailable ? { status: "unavailable", value: null, numerator: null, denominator: null, reason: "No mature cohort members in this reporting window." } : ratio ? { status: "available", value, numerator: ratio.length, denominator: cases.length } : { status: "available", value, numerator: null, denominator: null }, contributingRecords: refs.map((pointer) => ({ ...pointer, label: snapshot.reporters.find((person) => snapshot.acquisitionCases.find((acq) => acq.id === pointer.id)?.reporterId === person.id)?.fictionalName ?? pointer.id, occurredAt: snapshot.acquisitionCases.find((acq) => acq.id === pointer.id)?.openedAt ?? null, joinPath: [pointer] })), numeratorMembers: unavailable ? [] : ratio?.map(caseRef) ?? [], denominatorMembers: unavailable ? [] : ratio ? refs : [], exclusions: [], unknownCount: 0, limitations: ["Synthetic demonstration data; no real messages or policy decisions."], explanation, navigationTarget: { workspace: RECRUITING_WORKSPACE, intent: "work-list", filters, evidenceContext: { asOfAt: context.evaluation.asOfAt, snapshotRevision: context.evaluation.snapshotRevision, metric: definition } } }; }
export function prepareRecruitingWorkspace(snapshot: DemoSnapshotV2, context: WorkspaceQueryContext<typeof RECRUITING_WORKSPACE>): PreparedRecruitingView { const window = context.filters.window ?? { startAt: snapshot.baseAsOfAt, endAt: context.evaluation.asOfAt, boundary: "[start,end)" as const }; const currentCases = projectCurrentCases(snapshot, context.evaluation.asOfAt, context.filters.selectedMarket); const funnel = funnelProgression(snapshot, context.evaluation.asOfAt, window, context.filters.selectedMarket); const onboarding = onboardingOutcomes(snapshot, context.evaluation.asOfAt, window, context.filters.selectedMarket); const sources = sourceOutcomes(snapshot, context.evaluation.asOfAt, window, context.filters.selectedMarket); const ready = funnel.stages.find((item) => item.stage === "ready")!.caseIds; const firstJobs = globallyEarliestCompletedOutcomes(snapshot, context.evaluation.asOfAt); const firstJobCases = snapshot.acquisitionCases.filter((item) => firstJobs.has(item.reporterId) && (context.filters.selectedMarket === "ALL" || item.ownerMarketId === context.filters.selectedMarket)).map((item) => item.id); const sourcedCases = sources.flatMap((source) => source.caseIds); return { workspace: RECRUITING_WORKSPACE, evaluation: context.evaluation, appliedFilters: context.filters, currentCases, funnel, onboarding, sources, evidence: [bundle(snapshot, context, "M05", firstJobCases.length, firstJobCases, window, "Each reporter contributes only their globally earliest valid completed job; recruiting ownership is fixed at case entry."), bundle(snapshot, context, "M06", currentCases.filter((item) => item.openActions.length > 0).length, currentCases.filter((item) => item.openActions.length > 0).map((item) => item.acquisitionCaseId), null, "Current actionable cases have a concrete unmet step, unresolved information, or open work."), bundle(snapshot, context, "M07", funnel.matureCaseIds.length ? ready.length / funnel.matureCaseIds.length : 0, funnel.matureCaseIds, window, "Finalized conversion uses only cases observed for a full 30 days.", ready), bundle(snapshot, context, "M08", onboarding.rate ?? 0, onboarding.matureCaseIds, window, "Within-14-day outcomes use globally earliest completed jobs; observing entrants stay separate.", onboarding.timelyCaseIds), bundle(snapshot, context, "M09", sourcedCases.length, sourcedCases, window, "Source outcomes use the source fixed when each first-time acquisition case opened; recorded direct spend is never treated as free when absent.")] }; }
